version: '3.9'

services:
  db:
    container_name: semantic_db
    platform: linux/amd64
    image: mysql:8
    restart: always
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: semantic_web
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    links:
     - db
