create table cities (
  id int not null,
  name varchar(255) not null,
  primary key(id)
 )


insert into cities
(id, name)
values
(0, "Quảng Ninh"),
(1, "Hải Phòng"),
(2, "Thái Bình"),
(3, "Nam Định"),
(4, "Ninh Bình"),
(5, "Thanh Hóa"),
(6, "Nghệ An"),
(7, "Hà Tĩnh"),
(8, "Quảng Bình"),
(9, "Quảng Trị"),
(10, "Thừa Thiên Huế"),
(11, "Đà Nẵng"),
(12, "Quảng Nam"),
(13, "Quảng Ngãi"),
(14, "Bình Định"),
(15, "Phú Yên"),
(16, "Khánh Hòa"),
(17, "Ninh Thuận"),
(18, "Bình Thuận"),
(19, "Bà Rịa - Vũng Tàu"),
(20, "Thành phố Hồ Chí Minh"),
(21, "Tiền Giang"),
(22, "Trà Vinh"),
(23, "Cà Mau"),
(24, "Kiên Giang"),
(25, "Các bãi ngầm ngoài khơi Nam Bộ")

Create table islands (
  id int not null,
  name varchar(255) not null,
  latitude varchar(255),
  longitude varchar(255),
  summary text,
  cityId int not null,
  primary key(id)
);

insert into islands
(id, name, latitude, longitude, summary, cityId)
values
( 0, "Bãi Lục Lầm", "21°32′25″B", "108°01′45″Đ", "", 0),
( 1, "Đảo Vĩnh Thực", "21°22′24″B", "107°54′49″Đ", "Đảo Vĩnh Thực là một hòn đảo thuộc địa phận tỉnh Quảng Ninh, cách trung tâm thành phố Móng Cái khoảng 20 km về phía nam. Đảo Vĩnh Thực có diện tích tự nhiên khoảng 5.000 ha, về mặt hành chính gồm 2 xã Vĩnh Thực và Vĩnh Trung, đều thuộc thành phố Móng Cái.[1]", 0),
( 2, "Đảo Miều", "21°22′00″B", "107°45′16″Đ", "", 0),
( 3, "Đảo Cái Chiên", "21°19′45″B", "107°46′05″Đ", "Cái Chiên là một xã đảo thuộc huyện Hải Hà, tỉnh Quảng Ninh, Việt Nam.", 0),
( 4, "Đảo Thoi Xanh", "21°17′32″B", "107°46′02″Đ", "", 0),
( 5, "Đảo Vạn Mực", "21°17′12″B", "107°40′31″Đ", "", 0),
( 6, "Đảo Vạn Nước", "21°16′39″B", "107°39′33″Đ", "", 0),
( 7, "Đảo Gội", "21°17′02″B", "107°31′06″Đ", "", 0),
( 8, "Đảo Sú Một", "21°17′01″B", "107°30′20″Đ", "", 0),
( 9, "Đảo Vạn Vược", "21°14′44″B", "107°36′59″Đ", "", 0),
( 10, "Đảo Cái Bầu", "21°09′53″B", "107°29′35″Đ", "", 0),
( 11, "Đảo Cái Lim", "21°05′58″B", "107°33′14″Đ", "", 0),
( 12, "Đảo Quan Lạn", "20°54′10″B", "107°31′05″Đ", "Đảo Quan Lạn hay đảo Cảnh Cước là một hòn đảo trên vịnh Bái Tử Long huyện Vân Đồn tỉnh Quảng Ninh, miền bắc Việt Nam.[1][2][3][4]", 0),
( 13, "Đảo Cao Lô", "21°04′05″B", "107°35′56″Đ", "", 0),
( 14, "Đảo Cặp Tiên", "21°03′34″B", "107°33′12″Đ", "", 0),
( 15, "Đảo Cặp Tiên Ngoài", "21°02′11″B", "107°22′21″Đ", "", 0),
( 16, "Đảo Cặp Tiên Trong", "21°02′46″B", "107°22′29″Đ", "", 0),
( 17, "Đảo Chàng Ngọ", "21°07′42″B", "107°33′55″Đ", "", 0),
( 18, "Đảo Cống Đông", "20°53′59″B", "107°18′48″Đ", "", 0),
( 19, "Đảo Cống Nứa", "20°57′34″B", "107°28′08″Đ", "", 0),
( 20, "Đảo Cống Tây", "20°53′30″B", "107°18′20″Đ", "", 0),
( 21, "Đảo Đá Trắng", "21°05′32″B", "107°27′32″Đ", "", 0),
( 22, "Đảo Đầu Nam", "21°01′00″B", "107°28′10″Đ", "", 0),
( 23, "Đảo Đồng Chén", "20°56′23″B", "107°25′35″Đ", "", 0),
( 24, "Đảo Đông Ma", "21°08′54″B", "107°34′59″Đ", "", 0),
( 25, "Đảo Giàn Mướp", "20°50′15″B", "107°21′32″Đ", "", 0),
( 26, "Đảo Hạ Mai", "20°43′32″B", "107°27′34″Đ", "", 0),
( 27, "Đảo Lão Vọng", "21°03′16″B", "107°31′07″Đ", "", 0),
( 28, "Đảo Lồ Con", "20°53′34″B", "107°20′43″Đ", "", 0),
( 29, "Đảo Mang", "20°54′07″B", "107°30′00″Đ", "", 0),
( 30, "Đảo Muy Tin", "21°12′10″B", "107°25′33″Đ", "", 0),
( 31, "Đảo Nam Hải", "21°00′23″B", "107°26′07″Đ", "", 0),
( 32, "Đảo Nất Đất", "20°45′08″B", "107°23′33″Đ", "", 0),
( 33, "Đảo Ngọc Vừng", "20°49′07″B", "107°22′02″Đ", "", 0),
( 34, "Đảo Phượng Hoàng", "20°47′35″B", "107°24′40″Đ", "", 0),
( 35, "Đảo Sậu Nam", "21°10′42″B", "107°39′54″Đ", "", 0),
( 36, "Đảo Tàn Hoi", "21°01′13″B", "107°26′35″Đ", "", 0),
( 37, "Đảo Thẻ Vàng", "20°56′12″B", "107°21′21″Đ", "", 0),
( 38, "Đảo Thượng Mai", "20°45′50″B", "107°28′54″Đ", "", 0),
( 39, "Đảo Trà Bản", "20°57′43″B", "107°30′20″Đ", "", 0),
( 40, "Đảo Vạn Cảnh", "20°52′36″B", "107°21′32″Đ", "", 0),
( 41, "Đảo Vân Đồn", "20°51′04″B", "107°24′48″Đ", "", 0),
( 42, "Đảo Vạn Đuối", "20°55′14″B", "107°19′49″Đ", "", 0),
( 43, "Đảo Cái Mắt", "21°16′22″B", "107°26′03″Đ", "", 0),
( 44, "Đảo Đồng Rui", "21°13′35″B", "107°23′49″Đ", "", 0),
( 45, "Đảo Hà Loan", "21°09′12″B", "107°23′56″Đ", "", 0),
( 46, "Đảo Đầu Bê", "20°45′12″B", "107°08′10″Đ", "", 0),
( 47, "Đảo Đầu Gỗ", "20°54′23″B", "107°01′13″Đ", "", 0),
( 48, "Đảo Bồ Hòn", "20°50′23″B", "107°06′02″Đ", "", 0),
( 49, "Đảo Cống Đỏ", "20°52′37″B", "107°11′56″Đ", "", 0),
( 50, "Đảo Hang Trai", "20°47′14″B", "107°07′22″Đ", "", 0),
( 51, "Đảo Lõm Bò", "20°50′05″B", "107°04′46″Đ", "", 0),
( 52, "Đảo Tùng Lâm", "20°52′23″B", "107°00′36″Đ", "", 0),
( 53, "Đảo Tuần Châu", "20°55′45″B", "106°59′21″Đ", "Tuần Châu là một phường đảo thuộc thành phố Hạ Long, Quảng Ninh, Việt Nam. Tuần Châu hiện trở thành một khu du lịch, nghỉ dưỡng của Hạ Long.", 0),
( 54, "Đảo Vạn Giò", "20°50′25″B", "107°16′44″Đ", "", 0),
( 55, "Hòn Rều", "20°59′06″B", "107°18′41″Đ", "Đảo Rều hay hòn Rều là nhóm đảo trong vịnh Bái Tử Long, thuộc vùng đất phường Cẩm Sơn thành phố Cẩm Phả tỉnh Quảng Ninh, Việt Nam.[1]", 0),
( 56, "Hòn Rều Đất", "20°58′52″B", "107°19′13″Đ", "Đảo Rều hay hòn Rều là nhóm đảo trong vịnh Bái Tử Long, thuộc vùng đất phường Cẩm Sơn thành phố Cẩm Phả tỉnh Quảng Ninh, Việt Nam.[1]", 0),
( 57, "Đảo Cô Tô", "", "", "", 0),
( 58, "Đảo Thanh Lân", "", "", "", 0),
( 59, "Đảo Bạch Long Vĩ", "20°07′44″B", "107°43′45″Đ", "Bạch Long Vĩ là một đảo đồng thời là một huyện thuộc thành phố Hải Phòng, Việt Nam.[2] Đây là đảo xa bờ nhất trong vịnh Bắc Bộ, nằm ở khoảng giữa vịnh, cách hòn Dáu (Hải Phòng) 110 km, cách đảo Hạ Mai (Vân Đồn, Quảng Ninh) 70 km và cách mũi Đại Giác[Ghi chú 1] trên đảo Hải Nam (Trung Quốc) 130 km. Đảo nằm trên một trong tám ngư­ trường lớn của vịnh, có vị trí quan trọng trong chiến lược phát triển kinh tế, an ninh - quốc phòng biển của Việt Nam ở vịnh Bắc Bộ cũng như trong phân định vịnh Bắc Bộ.", 1),
( 60, "Hòn Dáu", "20°40′02″B", "106°48′59″Đ", "Hòn Dáu[1] hay Hòn Dấu là hòn đảo nằm trong vịnh Bắc Bộ thuộc khu du lịch giải trí Đồ Sơn, thành phố Hải Phòng, Việt Nam. Phần lớn đảo vẫn đang ở trạng thái nguyên sinh. Trên đảo có đền thờ Nam Hải Đại Vương, có ngọn hải đăng và một số di tích khác.", 1),
( 61, "Cồn Hoa", "20°40′54″B", "106°48′35″Đ", "", 1),
( 62, "Cồn Mục", "20°39′05″B", "106°44′44″Đ", "", 1),
( 63, "Quần đảo Cát Bà", "20°47′37″B", "107°00′30″Đ", "Cát Bà có thể là:", 1),
( 64, "Đảo Quả Muỗm", "20°51′21″B", "106°53′20″Đ", "", 1),
( 65, "Đảo Quả Xoài", "20°51′06″B", "106°54′51″Đ", "", 1),
( 66, "Quần đảo Long Châu", "20°37′22″B", "107°09′30″Đ", "Quần đảo Long Châu là một quần đảo cấu tạo từ đá vôi gồm khoảng trên 30 đảo, đá, bãi ngầm nằm cách Cát Bà 15 km về phía đông nam và cách bờ biển Hải Phòng 50 km.[1][2][3]", 1),
( 67, "Đảo Long Châu Đông", "20°36′57″B", "107°12′18″Đ", "", 1),
( 68, "Hòn Long Châu Bắc", "20°39′04″B", "107°07′58″Đ", "", 1),
( 69, "Hòn Long Châu Nam", "20°37′00″B", "107°10′07″Đ", "", 1),
( 70, "Hòn Long Châu Tây", "20°36′59″B", "107°07′50″Đ", "", 1),
( 71, "Đảo Quả Muỗm", "20°51′21″B", "106°53′20″Đ", "", 1),
( 72, "Đảo Quả Xoài", "20°51′06″B", "106°54′51″Đ", "", 1),
( 73, "Đảo Long Châu Đông", "20°36′57″B", "107°12′18″Đ", "", 1),
( 74, "Hòn Long Châu Bắc", "20°39′04″B", "107°07′58″Đ", "", 1),
( 75, "Hòn Long Châu Nam", "20°37′00″B", "107°10′07″Đ", "", 1),
( 76, "Hòn Long Châu Tây", "20°36′59″B", "107°07′50″Đ", "", 1),
( 77, "Cồn Đen", "20°28′59″B", "106°36′17″Đ", "Cồn Đen được hình thành do kiến tạo bồi đắp phù sa và bùn cát của sông Trà Lý dưới tác động của dòng chảy giữa sông và chế độ thủy động lực vùng ven biển tạo thành nên có địa hình tương đối bằng phẳng. Phía Nam của cồn cát hiện nay vẫn đang tiếp tục được bồi tụ và phát triển dài dưới dạng các mũi cát chạy song song với đường bờ. ", 2),
( 78, "Cồn Vành", "20°16′30″B", "106°36′03″Đ", "Cồn Vành được hình thành do kiến tạo bồi đắp phù sa và bùn cát của sông Hồng dưới tác động của dòng chảy giữa sông và chế độ thủy động lực vùng ven biển tạo thành nên có địa hình tương đối bằng phẳng. ", 2),
( 79, "Cồn Thủ", "20°26′50″B", "106°37′29″Đ", "", 2),
( 80, "Cồn Ngạn", "20°13′01″B", "106°35′43″Đ", "", 3),
( 81, "Cồn Lu", "20°12′17″B", "106°32′58″Đ", "", 3),
( 82, "Cồn Mờ", "20°11′38″B", "106°33′24″Đ", "", 3),
( 83, "Cồn Xanh", "", "", "", 3),
( 84, "Cồn Mờ", "19°54′58″B", "106°08′01″Đ", "", 4),
( 85, "Cồn Trời", "19°53′48″B", "106°06′48″Đ", "", 4),
( 86, "Cồn Nổi", "19°52′08″B", "106°04′11″Đ", "Cồn Nổi là một hòn đảo thuộc vùng biển tỉnh Ninh Bình, từ năm 2019 được nối với đất liền bằng một cầu vượt biển dài 6 km. Khu sinh cảnh Bãi ngang - Cồn Nổi Kim Sơn đã được UNESCO công nhận là khu dự trữ sinh quyển thế giới châu thổ sông Hồng đồng thời trở thành khu kinh tế ven biển của Ninh Bình. Cồn Nổi đang được đầu tư xây dựng thành một điểm du lịch nghỉ dưỡng và hướng tới trở thành đô thị du lịch loại V theo Quy hoạch đô thị Ninh Bình.", 4),
( 87, "Hòn Chó", "", "", "", 6),
( 88, "Hòn Sục hay đảo Sụp, hòn Sụp", "", "", "", 6),
( 89, "Cồn Niêu", "", "", "", 6),
( 90, "Hòn Mạn", "", "", "", 6),
( 91, "Hòn Chóp Mẹ", "", "", "", 7),
( 92, "Hòn Chóp Con", "", "", "", 7),
( 93, "Hòn Chùa", "", "", "", 8),
( 94, "Hòn Núc", "", "", "", 8),
( 95, "Đảo Cồn Cỏ", "17°09′35″B", "107°20′19″Đ", "Cồn Cỏ là một huyện đảo thuộc tỉnh Quảng Trị, Việt Nam.", 9),
( 96, "Hòn Sẹo", "", "", "", 14),
( 97, "Hòn Nước", "", "", "", 14),
( 98, "Hòn Mù U", "", "", "", 15),
( 99, "Hòn Sụn", "", "", "", 15),
( 100, "Quần đảo Trường Sa", "", "", "Quần đảo Trường Sa (tiếng Anh: Spratly Islands; giản thể: 南沙群岛; phồn thể: 南沙群島; Hán-Việt: Nam Sa Quần đảo; bính âm: Nánshā Qúndǎo; tiếng Mã Lai và tiếng Indonesia: Kepulauan Spratly; tiếng Tagalog: Kapuluan ng Kalayaan) là một tập hợp các thực thể địa lý được bao quanh bởi những vùng ngư nghiệp trù phú đồng thời sở hữu trữ lượng dầu mỏ, khí đốt lớn thuộc biển Đông. Ngày nay, quần đảo này hiện đang ở trong tình trạng tranh chấp lãnh thổ ở các mức độ khác nhau giữa 6 quốc gia, lần lượt là: Brunei, Trung Hoa Dân Quốc (Đài Loan), Cộng hoà Nhân dân Trung Hoa (Trung Quốc), Malaysia, Philippines và Việt Nam.", 16),
( 101, "Quần đảo Phú Quý", "", "", "Phú Quý là một huyện đảo thuộc tỉnh Bình Thuận, Duyên hải Nam Trung Bộ, Việt Nam và là một quần đảo gồm 12 đảo lớn nhỏ, nằm ngoài cùng hệ thống đảo ở cực Nam Trung Bộ.", 18),
( 102, "Đảo Phú Quý", "10°31′32″B", "108°56′36″Đ", "", 18),
( 103, "Hòn Tranh", "10°29′30″B", "108°58′00″Đ", "", 18),
( 104, "Hòn Câu hay Cù lao Câu", "11°13′33″B", "108°49′39″Đ", "", 18),
( 105, "Hòn Lao hay Hòn Ghềnh", "10°54′36″B", "108°18′02″Đ", "Hòn Lao hay còn gọi là Hòn Lau, Hòn Ghềnh, là một đảo đá nhỏ ven bờ Biển Đông, thuộc tỉnh Bình Thuận.[1][2]", 18),
( 106, "Hòn Bà", "10°41′45″B", "107°59′32″Đ", "Hòn Bà tại Việt Nam có thể là:", 18),
( 107, "Hòn Nghề", "11°01′31″B", "108°22′13″Đ", "Hòn Nghề[1], Hòn Rùa, Hòn Quy, Hòn Đú hay Hòn Ghe, là một đảo đá nhỏ ven bờ Biển Đông, thuộc tỉnh Bình Thuận.[2] Đảo có hình một con rùa quay đầu ra biển.[3] Diện tích đảo khoảng 8.000 m2, cách bờ biển Bình Thuận chỉ hơn 120 mét. Đảo có độ cao 15 m so với mực nước biển,[4] không có người ở. Hòn Nghề cách Đồi cát bay Mũi Né 12 km về hướng tây nam và cách hồ Bàu Trắng 7 km về hướng đông bắc. Hòn Nghề thuộc địa phận thôn Hồng Chính, ấp Thiện Ái, xã Hòa Thắng, huyện Bắc Bình.", 18),
( 108, "Đảo Gò Găng, là cồn sông.", "", "", "Đảo Gò Găng là một địa điểm tọa lạc tại địa phận xã Long Sơn, Vũng Tàu và nằm cách trung tâm Vũng Tàu khoảng 3 km về phía Tây Nam. Tổng diện tích 30 km2 cùng với việc 3 mặt giáp sông và 1 mặt giáp biển tạo nên hệ thống mạng lưới giao thông đường thủy khá hoàn thiện, đảo Gò Găng được thiên nhiên ưu đãi tạo nên một vị thế chiến lược trong việc phát triển nền kinh tế biển. Bên cạnh đó, Gò Găng không chỉ có biển mà còn có hệ thống rừng, ao hồ. Điều này mang lại mang lại một lợi thế không nhỏ đến sự phát triển du lịch phía Tây Nam của Vũng Tàu.", 19),
( 109, "Bãi Ngựa", "10°24′45″B", "107°06′04″Đ", "", 19),
( 110, "Cù lao Tào", "10°23′47″B", "107°05′48″Đ", "Cù lao Tào là một đảo nhỏ gần bờ, nằm trong vịnh Gành Rái về phía đông. Đảo có hình thon dài từ bắc xuống nam, cách bờ 350 mét, diện tích 20,0 ha (0,2 km2). Đảo được quản lý bởi chính quyền Thành phố Vũng Tàu.[1]", 19),
( 111, "Hòn Bà", "10°19′26″B", "107°05′21″Đ", "Hòn Bà là một đảo đá nhỏ gần bờ biển của Thành phố Vũng Tàu,[1][2][3] cách bờ khoảng 220 mét, diện tích 5.450 m 2. Trên đảo có một ngôi miếu, gọi là Miếu Hòn Bà.[4]", 19),
( 112, "Quần đảo Côn Đảo", "", "", "Côn Đảo là một quần đảo ở ngoài khơi bờ biển Nam Bộ và cũng là đơn vị hành chính cấp huyện trực thuộc tỉnh Bà Rịa – Vũng Tàu.", 19),
( 113, "Cụm đảo Hòn Trứng", "", "", "Côn Đảo là một quần đảo ở ngoài khơi bờ biển Nam Bộ và cũng là đơn vị hành chính cấp huyện trực thuộc tỉnh Bà Rịa – Vũng Tàu.", 19),
( 114, "Hòn Trứng Lớn", "", "", "Côn Đảo là một quần đảo ở ngoài khơi bờ biển Nam Bộ và cũng là đơn vị hành chính cấp huyện trực thuộc tỉnh Bà Rịa – Vũng Tàu.", 19),
( 115, "Hòn Trứng Nhỏ", "", "", "Côn Đảo là một quần đảo ở ngoài khơi bờ biển Nam Bộ và cũng là đơn vị hành chính cấp huyện trực thuộc tỉnh Bà Rịa – Vũng Tàu.", 19),
( 116, "Cụm đảo Hòn Trứng", "", "", "Côn Đảo là một quần đảo ở ngoài khơi bờ biển Nam Bộ và cũng là đơn vị hành chính cấp huyện trực thuộc tỉnh Bà Rịa – Vũng Tàu.", 19),
( 117, "Hòn Trứng Lớn", "", "", "Côn Đảo là một quần đảo ở ngoài khơi bờ biển Nam Bộ và cũng là đơn vị hành chính cấp huyện trực thuộc tỉnh Bà Rịa – Vũng Tàu.", 19),
( 118, "Hòn Trứng Nhỏ", "", "", "Côn Đảo là một quần đảo ở ngoài khơi bờ biển Nam Bộ và cũng là đơn vị hành chính cấp huyện trực thuộc tỉnh Bà Rịa – Vũng Tàu.", 19),
( 119, "Đảo Thạnh An, là vùng cửa sông, không phải đảo thật sự.", "", "", "Thạnh An là một xã thuộc huyện Cần Giờ, Thành phố Hồ Chí Minh, Việt Nam.", 20),
( 120, "Cồn Ngang", "10°12′55″B", "106°47′36″Đ", "Cồn Ngang là một bãi bồi ở vùng cửa sông Mekong thuộc huyện Tân Phú Đông, tỉnh Tiền Giang, Việt Nam.[1][2]", 21),
( 121, "Cồn Nghêu", "10°10′15″B", "106°49′38″Đ", "", 22),
( 122, "Quần đảo Hòn Khoai", "8°26′08″B", "104°49′59″Đ", "Quần đảo Hòn Khoai (tên cũ: Giáng Hương, Ile Independence, Paulo Obi, Pulo Ubi, Pulo Oby)[1][2][3][4][5] là tên một cụm đảo thuộc tỉnh Cà Mau, trong đó đảo chính là Hòn Khoai.[6]", 23),
( 123, "Hòn Rùa", "8°25′14″B", "104°51′44″Đ", "", 23),
( 124, "Hòn Sao", "8°24′57″B", "104°51′05″Đ", "", 23),
( 125, "Hòn Đá Lẻ", "8°22′44″B", "104°52′25″Đ", "", 23),
( 126, "Hòn Chuối", "8°57′03″B", "104°31′32″Đ", "Hòn Chuối là một hòn đảo trong vịnh Thái Lan, thuộc chủ quyền Việt Nam, nằm ngoài khơi phía tây bờ biển Cà Mau.[1][2]", 23),
( 127, "Hòn Đá Bạc", "9°10′45″B", "104°48′01″Đ", "Hòn Đá Bạc thuộc ấp Kinh Hòn, xã đảo Khánh Bình Tây, huyện Trần Văn Thời, tỉnh Cà Mau, Việt Nam.[1][2]", 23),
( 128, "Hòn Buông", "8°52′54″B", "104°33′46″Đ", "", 23),
( 129, "Hòn Rùa", "8°25′14″B", "104°51′44″Đ", "", 23),
( 130, "Hòn Sao", "8°24′57″B", "104°51′05″Đ", "", 23),
( 131, "Hòn Đá Lẻ", "8°22′44″B", "104°52′25″Đ", "", 23),
( 132, "Đảo Phú Quốc", "", "", "Phú Quốc là hòn đảo lớn nhất Việt Nam, nằm trong vịnh Thái Lan. Đảo Phú Quốc cùng với các đảo nhỏ hơn ở lân cận và quần đảo Thổ Chu nằm cách đó 55 hải lý về phía tây nam hợp thành thành phố Phú Quốc thuộc tỉnh Kiên Giang. Đây cũng là thành phố đảo đầu tiên của Việt Nam.", 24),
( 133, "Hòn Một", "", "", "Hòn Một là một hòn đảo nhỏ ven bờ của đảo Phú Quốc, nằm sát bờ, vị trí đông bắc đảo Phú Quốc.[1] Đảo cách bờ chỉ khoảng 200 mét nhưng hiện nay do bồi tụ của cát, khoảng cách chỉ còn chừng 100 mét. Diện tích đảo 6,8 ha, bao phủ bởi rừng.", 24),
( 134, "Hòn Móng Tay", "", "", "", 24),
( 135, "Hòn Bần hay Hòn Bàng", "", "", "Hòn Bần, hay Hòn Bàng, là một hòn đảo nhỏ trong vịnh Thái Lan, thuộc chủ quyền Việt Nam. Đảo nằm về phía tây bắc đảo Phú Quốc, cách bờ biển đảo Phú Quốc 2,3 km, cách Bãi biển Gành Dầu trên đảo Phú Quốc 2,76 km. Hòn Bần có diện tích gần 1,0 ha (0,01 km2), có hình thon dài như một con cá, đường bờ biển dài khoảng 600 mét. Tọa độ 10°13′20″B 103°29′03″Đ / 10,22214°B 103,4843°Đ / 10.22214; 103.48430.[1]", 24),
( 136, "Hòn Thầy Bói", "", "", "Hòn Thầy Bói, là một hòn đảo nhỏ trong vịnh Thái Lan, thuộc chủ quyền Việt Nam. Đảo nằm về phía tây bắc đảo Phú Quốc, cách bờ biển đảo Phú Quốc 2,67 km, cách Hòn Bần 1,53 km về hướng bắc, chệch hướng đông bắc. Hòn Thầy Bói là một hòn đảo nhỏ, chỉ có diện tích khoảng 3.700 m2, đường bờ biển dài khoảng 250 mét. Tọa độ 10°21′31″B 103°48′31″Đ / 10,358603°B 103,808666°Đ / 10.358603; 103.808666.[1]", 24),
( 137, "Hòn Đồi Mồi", "10°19′24″B", "103°50′21″Đ", "Hòn Đồi Mồi là một hòn đảo nhỏ trong vịnh Thái Lan, nằm ven biển phía tây đảo Phú Quốc,[1] cách bờ biển Bãi Dài của Phú Quốc 1 km. Diện tích khoảng 2.500 m2.[2][3]", 24),
( 138, "Hòn Nghệ", "10°01′39″B", "104°33′11″Đ", "Hòn Nghệ là một xã thuộc huyện Kiên Lương, tỉnh Kiên Giang, Việt Nam.[3][4]", 24),
( 139, "Hòn Tre, Kiên Hải", "9°58′02″B", "104°50′20″Đ", "Hòn Tre là một xã đảo thuộc huyện Kiên Hải, tỉnh Kiên Giang, Việt Nam.", 24),
( 140, "Hòn Rái", "9°48′13″B", "104°38′20″Đ", "Lại Sơn là một xã thuộc huyện Kiên Hải, tỉnh Kiên Giang, Việt Nam.", 24),
( 141, "Quần đảo An Thới", "", "", "Quần đảo An Thới là quần đảo trong vịnh Thái Lan, nằm dưới sự quản lý của phường An Thới, thành phố Phú Quốc, tỉnh Kiên Giang, Việt Nam.[1][2]", 24),
( 142, "Hòn Móng Tay", "", "", "", 24),
( 143, "Quần đảo Hà Tiên hay quần đảo Hải Tặc", "", "", "Quần đảo Hà Tiên hay quần đảo Hải Tặc là một quần đảo trong vịnh Thái Lan thuộc Việt Nam. Về hành chính quần đảo thuộc vùng đất xã Tiên Hải thành phố Hà Tiên, tỉnh Kiên Giang.", 24),
( 144, "Quần đảo Bà Lụa", "10°08′11″B", "104°31′38″Đ", "Quần đảo Bà Lụa là một quần đảo trong Vịnh Thái Lan thuộc lãnh thổ huyện Kiên Lương tỉnh Kiên Giang, Việt Nam.[1][2] Về hành chính quần đảo thuộc xã đảo Sơn Hải huyện Kiên Lương. Trung tâm của quần đảo cách mũi Hòn Chông khoảng 6 km về phía tây.", 24),
( 145, "Quần đảo Nam Du", "9°40′48″B", "104°21′06″Đ", "Quần đảo Nam Du là một quần đảo nằm về phía đông nam đảo Phú Quốc trong vịnh Thái Lan, cách bờ biển Rạch Giá 65 hải lý. Quần đảo nằm dưới sự quản lý của xã An Sơn và xã Nam Du thuộc huyện Kiên Hải, tỉnh Kiên Giang.", 24),
( 146, "Quần đảo Thổ Chu", "", "", "Quần đảo Thổ Chu[2] hay quần đảo Thổ Châu là một quần đảo nằm trong vịnh Thái Lan, ở về phía tây nam đảo Phú Quốc và được xem là ở cực tây nam của Việt Nam. Toàn bộ quần đảo này cấu thành xã đảo Thổ Châu, thành phố Phú Quốc, tỉnh Kiên Giang. Nằm cách bờ vịnh Rạch Giá 198 km,[3] đảo Thổ Chu là đảo lớn nhất trong quần đảo và thường được ghi tên là Poulo Panjang (gốc từ tiếng Mã Lai Pulau Panjang, nghĩa là cù lao dài hoặc đảo dài) trên nhiều hải đồ của người phương Tây[4] từ các thế kỉ trước.", 24),
( 147, "Hòn Quéo, chỉ là mỏm đá sát biển.", "", "", "", 24),
( 148, "Đảo Ba Ba", "", "", "Đảo Ba Ba là một bãi cát thuộc nhóm đảo Lưỡi Liềm của quần đảo Hoàng Sa. Đảo này nằm cách đảo Ốc Hoa khoảng 1,6 km về phía đông nam và cách bãi Xà Cừ 2 km về phía tây nam.", 11),
( 149, "Đảo Bạch Quy", "", "", "Đảo Bạch Quy là một cồn cát nằm trên vành san hô của một rạn san hô vòng thuộc nhóm đảo Lưỡi Liềm của quần đảo Hoàng Sa. Đảo Bạch Quy cách đá Lồi 8,6 hải lý (15,9 km) về phía Nam.", 11),
( 150, "Đảo Bắc", "", "", "Đảo Bắc là một đảo san hô thuộc nhóm đảo An Vĩnh của quần đảo Hoàng Sa. Đảo này nằm cách đảo Cây khoảng 1,94 hải lý (3,6 km) về hướng đông đông nam.[1]", 11),
( 151, "Đảo Cây", "", "", "Đảo Cây là một đảo san hô thuộc nhóm đảo An Vĩnh của quần đảo Hoàng Sa. Đảo nằm cách đảo Phú Lâm khoảng 9,1 hải lý (16,9 km) về phía bắc tây bắc và cách cồn cát Tây 2,9 hải lý (5,4 km) về phía đông.[1]", 11),
( 152, "Đảo Duy Mộng", "", "", "Đảo Duy Mộng là một đảo san hô thuộc nhóm đảo Lưỡi Liềm của quần đảo Hoàng Sa. Đảo này nằm ở điểm cuối của một vòng cung san hô, ngay phía đông bắc của đảo Quang Hoà, cách đảo Quang Hòa 2,9 km.", 11),
( 153, "Đảo Đá", "", "", "Đảo Đá, như tên gọi của mình, là một đảo đá nhỏ thuộc nhóm đảo An Vĩnh, quần đảo Hoàng Sa. Đảo nằm trên cùng một bãi đá san hô với đảo Phú Lâm, cách Phú Lâm khoảng hơn 700 m về phía đông bắc. Nơi cao nhất của đảo Đá là 15,2 m (50 ft), cũng là nơi cao nhất Quần đảo Hoàng Sa.[1]", 11),
( 154, "Đảo Hoàng Sa", "", "", "Đảo Hoàng Sa là một đảo san hô thuộc nhóm đảo Lưỡi Liềm của quần đảo Hoàng Sa. Thời còn đô hộ Việt Nam, Pháp chọn đảo Hoàng Sa làm nơi đóng quân chính, viện lý do đảo gần đất liền, gần trung tâm của quần đảo và ở gần nhiều đảo khác nên kiểm soát dễ dàng hơn đảo Phú Lâm.[1]", 11),
( 155, "Đảo Hữu Nhật", "", "", "Đảo Hữu Nhật là một đảo san hô thuộc nhóm đảo Lưỡi Liềm của quần đảo Hoàng Sa. Đảo này nằm cách đảo Hoàng Sa khoảng 3,3 km về hướng tây nam[1] và cách đá Hải Sâm khoảng 1,2 km về hướng bắc.", 11),
( 156, "Đảo Linh Côn", "", "", "Đảo Linh Côn là một đảo san hô thuộc nhóm đảo An Vĩnh của quần đảo Hoàng Sa. Đảo này nằm cách đảo Phú Lâm ở khu trung tâm nhóm An Vĩnh hơn 23,8 hải lý (44,1 km) về phía đông nam. Theo số liệu so sánh của Trung Quốc thì đây là đảo có diện tích đứng thứ hai ở Hoàng Sa, chỉ sau đảo Phú Lâm.[1]", 11),
( 157, "Đảo Lưỡi Liềm", "", "", "", 11),
( 158, "Đảo Nam", "", "", "Đảo Nam là một đảo san hô thuộc nhóm đảo An Vĩnh của quần đảo Hoàng Sa. Đảo này nằm cách đảo Trung chỉ 700 m về phía đông nam.", 11),
( 159, "Đảo Ốc Hoa", "", "", "Đảo Ốc Hoa là một bãi cát thuộc nhóm đảo Lưỡi Liềm của quần đảo Hoàng Sa. Đảo cách đảo Hoàng Sa 4,2 hải lý (7,8 km) về phía đông bắc và cách bãi Xà Cừ 2,1 km về phía tây.", 11),
( 160, "Đảo Phú Lâm", "", "", "Đảo Phú Lâm là đảo lớn nhất quần đảo Hoàng Sa, và là đảo tự nhiên lớn nhất trong cả hai quần đảo Hoàng Sa và quần đảo Trường Sa. Đảo Phú Lâm là một trong hai đảo lớn nhất thuộc nhóm đảo An Vĩnh (Amphitrite Group) của quần đảo Hoàng Sa ở Biển Đông (đảo kia là đảo Linh Côn). Đảo có nhiều cây cối tươi tốt nên mang tên Phú Lâm. Đây là đảo quan trọng nhất của nhóm đảo An Vĩnh và quần đảo Hoàng Sa [1]. Trước đây đảo có chiều dài 1,7 km, chiều ngang 1,3 km. Trên đảo có nhiều chim biển cư trú nên có một lớp phân chim khá dày, đã từng có một công ty Nhật Bản đến khai thác phân chim tại đây.[1]", 11),
( 161, "Đảo Quang Ảnh", "", "", "Đảo Quang Ảnh là một đảo san hô thuộc nhóm đảo Lưỡi Liềm của quần đảo Hoàng Sa. Đảo này nằm về phía tây nam của đảo Hữu Nhật và đá Hải Sâm nhưng chệch ra bên ngoài vành san hô cong đặc trưng cho khu trung tâm nhóm Lưỡi Liềm.", 11),
( 162, "Đảo Quang Hòa", "", "", "Đảo Quang Hòa là một đảo san hô thuộc nhóm đảo Lưỡi Liềm của quần đảo Hoàng Sa. Đảo này nằm cách đảo Duy Mộng khoảng 1,55 hải lý (2,87 km) về phía tây nam. Đây là đảo lớn nhất khu trung tâm nhóm Lưỡi Liềm.[1]", 11),
( 163, "Đảo Tri Tôn", "", "", "Đảo Tri Tôn (tiếng Anh: Triton Island; giản thể: 中建岛; phồn thể: 中建島; Hán-Việt: Trung Kiến đảo; bính âm: Zhōngjiàn dǎo) là một cồn cát thuộc nhóm đảo Lưỡi Liềm, quần đảo Hoàng Sa. Đảo nằm ở cực tây và có diện tích đứng thứ ba trong số các đảo của Hoàng Sa. Đảo Tri Tôn là đối tượng tranh chấp giữa Việt Nam, Đài Loan và Trung Quốc. Hiện nay, Trung Quốc đang kiểm soát đảo này.", 11),
( 164, "Đảo Trung", "", "", "Đảo Trung là một đảo san hô thuộc nhóm đảo An Vĩnh của quần đảo Hoàng Sa. Đảo này nằm cách đảo Bắc chỉ 600 m về phía đông nam.", 11),
( 165, "Cồn cát Bắc", "", "", "Cồn Cát Bắc là một cồn cát thuộc nhóm đảo An Vĩnh, quần đảo Hoàng Sa. Cồn này nằm cách đảo Nam chỉ khoảng 670 m về phía đông nam.", 11),
( 166, "Cồn cát Nam", "", "", "Cồn Cát Nam là một cồn cát thuộc nhóm đảo An Vĩnh của quần đảo Hoàng Sa. Cồn này nằm cách cồn Cát Trung chỉ 200 m về phía nam.", 11),
( 167, "Cồn cát Tây", "", "", "Cồn Cát Tây là một cồn cát thuộc nhóm đảo An Vĩnh của quần đảo Hoàng Sa. Cồn này nằm cách đảo Cây khoảng 4 hải lý (7,4 km) về phía tây.[1] Theo Google Maps thì khoảng cách này chỉ là 2,92 hải lý (5,41 km).", 11),
( 168, "Cồn cát Trung", "", "", "Cồn Cát Trung là một cồn cát thuộc nhóm đảo An Vĩnh của quần đảo Hoàng Sa. Cồn này nằm cách cồn Cát Bắc chỉ 170 m về phía nam đông nam.", 11),
( 169, "Hòn Tháp", "", "", "Hòn Tháp là một hòn đá nổi thuộc nhóm đảo An Vĩnh của quần đảo Hoàng Sa. Hòn Tháp nằm cách đảo Linh Côn khoảng 7,4 hải lý (13,7 km) về phía tây nam, trong khoảng giữa từ đảo Linh Côn đến bãi Thủy Tề.", 11),
( 170, "Đá Bắc", "", "", "Đá Bắc hoặc bãi đá Bắc là một rạn san hô vòng thuộc nhóm đảo Lưỡi Liềm của quần đảo Hoàng Sa. Đá Bắc nằm cách đảo Hoàng Sa thuộc khu trung tâm nhóm Lưỡi Liềm khoảng 32,6 hải lý (60,4 km), cách đảo Phú Lâm thuộc khu trung tâm nhóm An Vĩnh khoảng 47 hải lý (87 km), cách bãi Ốc Tai Voi ở cực nam 91,8 hải lý (170 km) và là điểm cực bắc của cả quần đảo.", 11),
( 171, "Đá Bông Bay", "", "", "Đá Bông Bay là một rạn san hô vòng thuộc nhóm đảo An Vĩnh của quần đảo Hoàng Sa. Đá này nằm ở góc đông nam của quần đảo, cách đảo Phú Lâm thuộc khu trung tâm nhóm An Vĩnh gần 46,7 hải lý (86,5 km) về phía nam đông nam và cách đảo Quang Hòa thuộc khu trung tâm nhóm Lưỡi Liềm khoảng 48,6 hải lý (90 km) về phía đông nam.", 11),
( 172, "Đá Chim Én", "", "", "Đá Chim Én là một rạn san hô vòng thuộc nhóm đảo Lưỡi Liềm của quần đảo Hoàng Sa. Đá này cách đá Lồi 9,7 hải lý (18 km) về phía đông bắc và cách đảo Quang Hòa 16,2 hải lý (30 km) về phía đông nam.", 11),
( 173, "Đá Hải Sâm", "", "", "Đá Hải Sâm là một rạn san hô vòng thuộc nhóm đảo Lưỡi Liềm của quần đảo Hoàng Sa. Đá này nằm cách đảo Quang Ảnh khoảng 1,5 hải lý (2,8 km) về phía đông và cách đảo Hữu Nhật khoảng 0,5 hải lý (0,9 km) về phía nam.[1]", 11),
( 174, "Đá Lồi", "", "", "Đá Lồi là một rạn san hô vòng thuộc nhóm đảo Lưỡi Liềm, quần đảo Hoàng Sa. Đá này nằm cách đảo Quang Hoà thuộc khu trung tâm nhóm Lưỡi Liềm khoảng 14 hải lý (26 km) về phía nam. Đây được xem là rạn san hô lớn nhất quần đảo Hoàng Sa.", 11),
( 175, "Đá Sơn Kỳ", "", "", "", 11),
( 176, "Đá Trà Tây", "", "", "", 11),
( 177, "Đá Trương Nghĩa", "", "", "", 11),
( 178, "Bãi Châu Nhai", "", "", "Bãi Châu Nhai là một bãi ngầm thuộc nhóm đảo An Vĩnh của quần đảo Hoàng Sa. Bãi này nằm cách đá Bông Bay khoảng 15 hải lý (27,8 km) về hướng bắc[1] và cách bãi Thủy Tề khoảng 10 hải lý (18,5 km) về phía nam. Bãi nằm ở rìa của một rạn san hô vòng có đảo Linh Côn.[2]", 11),
( 179, "Bãi Đèn Pha", "", "", "", 11),
( 180, "Bãi Gò Nổi", "", "", "Bãi Gò Nổi là một bãi ngầm thuộc nhóm đảo An Vĩnh của quần đảo Hoàng Sa, nằm cách đảo Linh Côn 12,5 hải lý (23 km) về phía đông bắc.[1] Đây được xem là điểm cực đông của cả quần đảo.[2]", 11),
( 181, "Bãi Ngự Bình", "", "", "", 11),
( 182, "Bãi Ốc Tai Voi", "", "", "Bãi Ốc Tai Voi là một núi ngầm thuộc quần đảo Hoàng Sa, nằm cách đá Bông Bay 23 hải lý (42,6 km) về phía tây nam.[1] Đây được xem là điểm cực nam của cả quần đảo.[2]", 11),
( 183, "Bãi Quảng Nghĩa", "", "", "Bãi Quảng Nghĩa là một tập hợp ba bãi san hô ngầm riêng biệt thuộc nhóm đảo An Vĩnh của quần đảo Hoàng Sa. Bãi này nằm về phía nam của hòn Tháp và cách bãi Châu Nhai khoảng 5 hải lý (9,3 km) về hướng đông đông bắc.[1] Quảng Nghĩa là phiên âm Hán Việt tên gọi (廣義) của tỉnh Quảng Ngãi Nhà Nguyễn (廣義省).", 11),
( 184, "Bãi Thủy Tề", "", "", "Bãi Thủy Tề là một cặp bãi ngầm thuộc nhóm đảo An Vĩnh của quần đảo Hoàng Sa. Bãi này nằm về phía tây nam của hòn Tháp và phía bắc của bãi Châu Nhai, cách bãi Châu Nhai 11 hải lý (20,4 km).[1]", 11),
( 185, "Bãi Xà Cừ", "", "", "Bãi Xà Cừ[1] là một rạn san hô, trên đó có một cồn cát nhỏ nổi lên. Thực thể địa lý này được xếp vào nhóm đảo Lưỡi Liềm của quần đảo Hoàng Sa. Bãi Xà Cừ cách đảo Hoàng Sa 5,8 hải lý (10,7 km) về phía đông bắc và tạo thành đỉnh của vòng cung san hô đặc trưng cho nhóm Lưỡi Liềm.", 11),
( 186, "Đảo Song Tử Đông", "", "", "Song Tử Đông (tiếng Anh: Northeast Cay, tiếng Filipino: Parola, tiếng Trung: 北子岛; bính âm: Běizi dǎo, Hán-Việt: Bắc Tử đảo) là đảo san hô có diện tích lớn thứ năm trong quần đảo Trường Sa, có diện tích khoảng 12,7 ha[cần dẫn nguồn]. Các quốc gia Trung Quốc, Đài Loan, Philippines và Việt Nam đều đòi hỏi chủ quyền đối với đảo Song Tử Đông. Hiện đảo đang nằm dưới sự kiểm soát của Philippines.", 16),
( 187, "Đảo Song Tử Tây", "", "", "Song Tử Tây (tiếng Anh: Southwest Cay, tiếng Philippines: Pugad, tiếng Trung: 南子岛, Hán Việt: Nam Tử đảo) là một cồn san hô thuộc cụm Song Tử, quần đảo Trường Sa. Việt Nam hiện đang quản lý Đảo Song Tử Tây, được phân chia hành chính thành xã Song Tử Tây, huyện Trường Sa, tỉnh Khánh Hòa (tọa độ địa lí ghi trên bia chủ quyền đảo Song Tử Tây là 11°25′55″B 114°18′0″Đ / 11,43194°B 114,3°Đ / 11.43194; 114.30000). Đảo Song Tử Tây cách bán đảo Cam Ranh 318 hải lý, cách đảo Đá Nam 2,6 hải lý về hướng Tây Nam, cách đảo Song Tử Đông 3 km và có thể nhìn thấy đảo này ở đường chân trời.", 16),
( 188, "Đá Bắc", "", "", "Đá Bắc là một rạn san hô thuộc cụm Song Tử của quần đảo Trường Sa. Đá này nằm về phía đông bắc của đảo Song Tử Đông.", 16),
( 189, "Đá Nam", "", "", "Đá Nam (tiếng Anh: South Reef; tiếng Filipino: Timog; giản thể: 奈罗礁; phồn thể: 奈羅礁; bính âm: Nàiluó jiāo, Hán-Việt: Nại La tiêu) là một rạn san hô thuộc cụm Song Tử của quần đảo Trường Sa. Đá này nằm cách đảo Song Tử Tây khoảng 3 hải lý (5,55 km) về phía tây nam.", 16),
( 190, "Bãi Đinh Ba", "", "", "Bãi Đinh Ba là một rạn san hô vòng chìm ngập dưới nước, thuộc cụm Song Tử của quần đảo Trường Sa. Rạn vòng này nằm cách rạn Nguy Hiểm phía Bắc (tiếng Anh: North Danger Reef) khoảng 15 hải lý (28 km) về phía đông.[Ghi chú 1] Bãi Đinh Ba bị ngăn cách với bãi Núi Cầu gần đó bởi một kênh nước rộng 2 hải lý (3,7 km).[1]", 16),
( 191, "Bãi Núi Cầu", "", "", "Bãi Núi Cầu là một rạn san hô vòng chìm ngập dưới nước, thuộc cụm Song Tử của quần đảo Trường Sa. Rạn vòng này nằm cách rạn Nguy Hiểm phía Bắc (tiếng Anh: North Danger Reef) khoảng 13 hải lý (24 km) về phía đông.[Ghi chú 1] Một kênh nước rộng 2 hải lý (3,7 km) ngăn cách bãi Núi Cầu với bãi Đinh Ba gần đó.[1]", 16),
( 192, "Đảo Thị Tứ", "", "", "Đảo Thị Tứ là một đảo san hô thuộc cụm Thị Tứ của quần đảo Trường Sa. Đảo này xếp thứ hai trong quần đảo về mặt diện tích.", 16),
( 193, "Đá Cá Nhám", "", "", "Đá Cá Nhám[1] là một rạn san hô vòng thuộc cụm Loại Ta, quần đảo Trường Sa. Đá này nằm cách đảo Bến Lạc 12 hải lý (22,2 km) về phía tây nam.[2]", 16),
( 194, "Đá Cái Vung", "", "", "", 16),
( 195, "Đá Hoài Ân", "", "", "Đá Hoài Ân[1] là một rạn san hô thuộc cụm Thị Tứ của quần đảo Trường Sa. Đây là một rạn đá nửa nổi nửa chìm (cạn nước khi thủy triều thấp) có chiều dài khoảng 1,4 hải lý (2,6 km), chiều rộng khoảng 0,5 hải lý (0,93 km) và có một cồn cát nhỏ bên trên. Nằm cách đảo Thị Tứ 3,5 hải lý (6,5 km) về phía tây,[2] cồn cát mà có nơi gọi là Sandy Cay[3] này chỉ có chiều dài chưa đến 20 m.[4]", 16),
( 196, "Đá Trâm Đức", "", "", "Đá Trâm Đức (tiếng Anh: Meijiu Reef; tiếng Trung: 梅九礁, bính âm: Meijiu Jiao) là một rạn san hô thuộc cụm Thị Tứ của quần đảo Trường Sa. Đây là một rạn đá nửa nổi nửa chìm (cạn nước khi thủy triều thấp) rộng khoảng 1,8 km theo trục bắc-nam, dài khoảng 4 km theo trục đông-tây[1], có dạng hình chữ V với hướng mở về phía đông. Đá này nằm vế phía đông-bắc của đảo Thị Tứ khoảng 2,3 km. Tọa độ của rạn san hô này là 11°03′B 114°19′Đ / 11,05°B 114,317°Đ / 11.050; 114.317.", 16),
( 197, "Đá Tri Lễ", "", "", "", 16),
( 198, "Đá Vĩnh Hảo", "", "", "Đá Vĩnh Hảo (tiếng Anh: Eastern Reef; tiếng Trung: 铁峙礁, bính âm: Tiezhi Jiao) là một rạn san hô thuộc cụm Thị Tứ của quần đảo Trường Sa. Đây là một rạn san hô nửa nổi nửa chìm (cạn nước khi thủy triều thấp) dài khoảng 1,7 km theo trục đông-bắc xuống tây-nam, rộng khoảng 1,4 km theo trục tây-bắc xuống đông-nam[1]. Đá này nằm vế phía đông-bắc của đảo Thị Tứ khoảng 8,8 km. Tọa độ của rạn san hô này là 11°0425 N, 114°2056.", 16),
( 199, "Đá Xu Bi", "", "", "Đá Xu Bi[1] là một rạn san hô vòng thuộc cụm Thị Tứ của quần đảo Trường Sa. Đá này nằm cách đảo Thị Tứ khoảng 26 km về phía tây nam.", 16),
( 200, "Đảo Bến Lạc", "", "", "Đảo Bến Lạc[1] là một đảo san hô thuộc cụm Loại Ta của quần đảo Trường Sa. Đây là đảo đứng thứ ba về mặt diện tích trong quần đảo.", 16),
( 201, "Đảo Loại Ta", "", "", "Đảo Loại Ta[1] (tiếng Anh: Loaita Island (South Island of Horsburgh); tiếng Filipino: Kota; tiếng Trung: 南钥岛; bính âm: Nányào dǎo, Hán-Việt: Nam Thược đảo) là một đảo cát nhỏ thuộc cụm Loại Ta của quần đảo Trường Sa. Đây là đối tượng tranh chấp giữa Việt Nam, Đài Loan, Philippines và Trung Quốc. Hiện Philippines đang kiểm soát đảo này.[2]", 16),
( 202, "Đảo Loại Ta Tây", "", "", "Đảo Loại Ta Tây[1] (tiếng Anh: Loaita Cay; tiếng Tagalog: Melchora Aquino; tiếng Trung: 南钥沙洲; bính âm: Nanyao Shazhou) là một cồn cát nhỏ thuộc cụm Loại Ta của quần đảo Trường Sa. Rạn san hô nửa nổi nửa chìm (cạn nước khi thủy triều thấp) nơi đảo này tọa lạc trải rộng khoảng 1,5 hải lý[2] (2,8 km), có diện tích khoảng 1,5 km² [3] và nằm cách đảo chính Loại Ta 5 hải lý (9,3 km)[2] về phía tây bắc.", 16),
( 203, "Đá An Lão", "", "", "Đá An Lão[1] là một rạn san hô thuộc cụm Loại Ta của quần đảo Trường Sa. Đá này nằm ở đầu mút đông bắc của bãi Đường, cách bãi Loại Ta (tiếng Anh: Loaita Bank) khoảng 18 hải lý (33,3 km) về phía đông bắc.[2][Ghi chú 1]", 16),
( 204, "Đá An Nhơn", "", "", "Đá An Nhơn[1] là một rạn san hô - trên đó có một cồn cát nhỏ tọa lạc - thuộc cụm Loại Ta của quần đảo Trường Sa. Đá này nằm cách đảo chính Loại Ta 6,8 hải lý (12,6 km) về phía đông đông bắc.[2]", 16),
( 205, "Đá An Nhơn Bắc", "", "", "Đá An Nhơn Bắc[1] hoặc bãi An Nhơn Bắc hay đá Cuội[2] (tiếng Anh: chưa rõ; tiếng Trung: 库归礁; bính âm: Kùguī jiāo, Hán-Việt: Khố Quy tiêu) là một rạn san hô nửa nổi nửa chìm (cạn nước khi thủy triều thấp) thuộc cụm Loại Ta của quần đảo Trường Sa. Đá này nằm cách đá An Nhơn khoảng 4,5 hải lý (8,3 km) về phía đông bắc[3] với tổng diện tích vào khoảng 50 ha.[4] Giữa đá này và đá An Nhơn còn có một rạn san hô nhỏ hơn nhưng chưa rõ tên gọi.", 16),
( 206, "Đá An Nhơn Nam", "", "", "", 16),
( 207, "Đá Sa Huỳnh", "", "", "Đá Sa Huỳnh[1] là một rạn san hô thuộc cụm Loại Ta của quần đảo Trường Sa. Đá này nằm cách đảo chính Loại Ta khoảng 2,3 hải lý (4,3 km) về phía đông-đông bắc[2] và cách đá An Nhơn 4,4 hải lý (8,1 km) về phía tây nam.[3] Đá Sa Huỳnh trải rộng khoảng nửa hải lý[4] với diện tích khoảng 25 ha.[3] Một phần của đá sẽ cạn nước khi thủy triều thấp.[4]", 16),
( 208, "Đá Tân Châu", "", "", "", 16),
( 209, "Bãi Đường", "", "", "Bãi Đường[1] (tiếng Anh: chưa rõ; tiếng Trung: 长礁; bính âm: Cháng jiāo, Hán-Việt: Trường tiêu) là một rạn san hô lớn thuộc cụm Loại Ta của quần đảo Trường Sa. Rạn này nằm về phía đông của cụm Thị Tứ, phía tây của đảo Bến Lạc và phía bắc của đá An Nhơn. Ở đầu mút đông bắc của bãi Đường có một rạn san hô mang tên là đá An Lão.", 16),
( 210, "Bãi Loại Ta Nam", "", "", "Bãi Loại Ta Nam[1] (tiếng Anh: Loaita Nan) là một rạn san hô nửa nổi nửa chìm (cạn nước khi thủy triều thấp) thuộc cụm Loại Ta của quần đảo Trường Sa. Nằm cách rạn san hô chứa đảo Loại Ta Tây khoảng 0,8 hải lý (1,5 km) về phía tây nam,[2] rạn san hô Loại Ta Nam có chiều dài theo trục đông bắc-tây nam khoảng 1,75 hải lý (3,2 km), chiều rộng khoảng 1 hải lý[3] với tổng diện tích là 2,3 km².[4] Tại đây có một xác tàu đắm.[5]", 16),
( 211, "Đảo Ba Bình", "", "", "Đảo Ba Bình (theo cách gọi của Việt Nam) hay đảo Thái Bình (theo cách gọi của Đài Loan) là một đảo san hô thuộc cụm Nam Yết của quần đảo Trường Sa. Đảo này nằm cách đảo Sơn Ca 6,2 hải lý (11,5 km) về phía tây và cách đảo Nam Yết khoảng 11 hải lý (20,4 km) về phía đông bắc.[3] Đây là đảo có diện tích tự nhiên lớn nhất của quần đảo Trường Sa.", 16),
( 212, "Đảo Nam Yết", "", "", "
Nam Yết (tiếng Anh: Namyit Island; tiếng Filipino: Binago; giản thể: 鸿庥岛; phồn thể: 鴻庥島; bính âm: Hóngxiū dǎo, Hán-Việt: Hồng Hưu đảo) là một đảo san hô thuộc cụm Nam Yết của quần đảo Trường Sa. Đảo này nằm cách đảo Ba Bình khoảng 11,9 hải lý (22 km) về phía nam và cách đảo Sinh Tồn 18 hải lý (33,3 km) về phía bắc. Đi tàu thủy từ đất liền Việt Nam đến đảo mất hơn hai ngày và hai đêm.[1]", 16),
( 213, "Đảo Sơn Ca", "", "", "Sơn Ca (tiếng Anh: Sand Cay; tiếng Filipino: Bailan; tiếng Trung: 敦謙沙洲; bính âm: Dūnqiān shāzhōu, Hán-Việt: Đôn Khiêm sa châu) là một đảo cát nhỏ thuộc cụm Nam Yết của quần đảo Trường Sa. Đảo này nằm cách đảo Ba Bình và cảng Cam Ranh lần lượt là 6,6 hải lý (12,2 km) và 331 hải lý (613 km) về phía đông.", 16),
( 214, "Đá Chữ Thập", "", "", "Đá Chữ Thập là một rạn san hô thuộc cụm Nam Yết của quần đảo Trường Sa. Đá này nằm ở vị trí cách biệt với các thực thể khác của quần đảo, nằm về phía tây nam của bãi san hô Tizard (Tizard Bank) thuộc cụm Nam Yết và về phía đông bắc của cụm Trường Sa.", 16),
( 215, "Đá Đền Cây Cỏ", "", "", "Đá Đền Cây Cỏ là một rạn san hô thuộc cụm Nam Yết của quần đảo Trường Sa. Đá này nằm về phía tây của đá Ga Ven khoảng 36 hải lý (66,7 km) và về phía tây bắc của đá Lớn khoảng 17 hải lý (32 km).[1][2]", 16),
( 216, "Đá Én Đất", "", "", "Đá Én Đất là một rạn san hô thuộc cụm Nam Yết của quần đảo Trường Sa. Đá này có kích thước lớn nhất cụm,[1] nằm tại cực đông của cụm và cách đá Núi Thị khoảng 7 hải lý (13 km) về phía đông-đông nam.[2]", 16),
( 217, "Đá Ga Ven", "", "", "Đá Ga Ven là một rạn san hô (đá) thuộc cụm Nam Yết của quần đảo Trường Sa[1], nằm vế phía tây bắc đá Lạc khoảng 2,5 hải lý và nằm về phía tây của đảo Nam Yết với khoảng cách là 8,5 hải lý.[2]", 16),
( 218, "Đá Lạc", "", "", "Đá Ga Ven là một rạn san hô (đá) thuộc cụm Nam Yết của quần đảo Trường Sa[1], nằm vế phía tây bắc đá Lạc khoảng 2,5 hải lý và nằm về phía tây của đảo Nam Yết với khoảng cách là 8,5 hải lý.[2]", 16),
( 219, "Đá Lớn", "", "", "Đá Lớn (tiếng Anh: Discovery Great Reef; tiếng Filipino: Paredes; tiếng Trung: 大现礁; bính âm: Dàxiàn jiāo, Hán-Việt: Đại Hiện tiêu.) là một rạn san hô vòng thuộc cụm Nam Yết của quần đảo Trường Sa. Đá này nằm cách bán đảo Cam Ranh 286 hải lý, nằm về phía tây tây nam của đảo Nam Yết khoảng 32 hải lý, nằm về phía tây bắc của đảo Sinh Tồn khoảng 30 hải lý.", 16),
( 220, "Đá Nhỏ", "", "", "Đá Nhỏ (tiếng Anh:  Discovery Small Reef; tiếng Filipino: Gomez; tiếng Trung: 小现礁; bính âm: Xiǎoxiàn jiāo, Hán-Việt: Tiểu Hiện tiêu) là một rạn san hô thuộc cụm Nam Yết của quần đảo Trường Sa. Đá này nằm về phía đông của đá Lớn khoảng 11 hải lý (20 km)[1] và về phía tây nam của đá Ga Ven khoảng 16 hải lý.", 16),
( 221, "Đá Núi Thị", "", "", "Đá Núi Thị hay Đá Thị (tiếng Anh: Petley Reef; tiếng Filipino: Juan Luna; tiếng Trung: 舶兰礁; bính âm: Bólán jiāo, Hán-Việt: Bạc Lan tiêu) là một rạn san hô thuộc cụm Nam Yết của quần đảo Trường Sa. Đá này nằm cách đảo Sơn Ca khoảng 7 hải lý (13 km) về phía đông-đông bắc và cách bán đảo Cam Ranh 322 hải lý,.[1]", 16),
( 222, "Bãi/Đá Bàn Than", "", "", "Bãi Bàn Than, đá Bàn Than (theo cách gọi của Việt Nam[1][2]) hay Bãi Trung Châu, Trung Châu tiêu, đá Trung Châu (theo cách gọi của Đài Loan) là một rạn san hô với một cồn cát nhỏ không có người ở thuộc cụm Nam Yết của quần đảo Trường Sa. Bàn Than nằm giữa đảo Ba Bình và đảo Sơn Ca, cách bờ gần nhất của đảo Ba Bình khoảng 4,6 km về phía đông. Hiện tại, bãi Bàn Than đang do phía Đài Loan duy trì quyền kiểm soát trên thực tế.[3]", 16),
( 223, "Đảo Sinh Tồn", "", "", "Sinh Tồn (tiếng Anh: Sin Cowe Island, giản thể: 景宏岛; phồn thể: 景宏島; Hán-Việt: Cảnh Hoành đảo; bính âm: Jǐnghóng dǎo) là một hòn đảo trong cụm Sinh Tồn, quần đảo Trường Sa (tọa độ ghi trên bia chủ quyền là 9°53′7″B 114°19′47″Đ / 9,88528°B 114,32972°Đ / 9.88528; 114.32972). Đảo này cùng với các đảo, đá, bãi phụ cận về mặt tổ chức hành chính thuộc xã Sinh Tồn, huyện Trường Sa, tỉnh Khánh Hòa, cách đất liền 320 hải lý, cách đảo Sinh Tồn Đông 14 hải lý (26 km) về phía tây. Đảo này chỉ cách đá Gạc Ma khoảng 10,5 hải lý (19,4 km), nơi xảy ra vụ đụng độ giữa Trung Quốc và Việt Nam năm 1988.", 16),
( 224, "Đảo Sinh Tồn Đông", "", "", "Đảo Sinh Tồn Đông (tiếng Anh: Grierson Reef[1]; tiếng Filipino: Julian Felipe; tiếng Trung: 染青沙洲; bính âm: Rǎnqīng shāzhōu, Hán-Việt: Nhiễm Thanh sa châu) là một cồn cát thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đảo này nằm cách đảo Sinh Tồn khoảng 14 hải lý (26 km) về phía đông.[2]", 16),
( 225, "Đá An Bình", "", "", "Đá An Bình (tiếng Anh: Ross Reef; tiếng Trung: 染青东礁; bính âm: Rǎnqīng dōng jiāo, Hán-Việt: Nhiễm Thanh Đông tiêu) là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá này nằm ở phía nam tây nam đá Ba Đầu và phía đông của đảo Sinh Tồn Đông.", 16),
( 226, "Đá Ba Đầu", "", "", "Đá Ba Đầu là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đây là điểm mút đông bắc của cụm Sinh Tồn và là rạn san hô lớn nhất trong cụm.[1]", 16),
( 227, "Đá Bãi Khung", "", "", "Đá Bãi Khung (tiếng Anh: Holiday Reef; tiếng Trung: 长线礁; bính âm: Chángxiàn jiāo, Hán-Việt: Trường Tuyến tiêu) là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá nằm ở vùng đông bắc của cụm Sinh Tồn, ở phía tây của đá Ba Đầu và cách đảo Sinh Tồn khoảng 14 hải lý (25,9 km) về phía đông bắc.[1]", 16),
( 228, "Đá Bia", "", "", "Đá Bia là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá này nằm giữa đá Tư Nghĩa ở ngay phía đông bắc và đá Ken Nan ở ngay phía tây bắc[1].", 16),
( 229, "Đá Bình Khê", "", "", "Đá Bình Khê (tiếng Anh: Edmund Reef; tiếng Trung: 南门礁; bính âm: Nánmén jiāo, Hán-Việt: Nam Môn tiêu) là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá này nằm cách đảo Sinh Tồn gần 7 km về phía đông-đông bắc.", 16),
( 230, "Đá Bình Sơn", "", "", "Đá Bình Sơn (tiếng Anh: Hallet Reef; tiếng Trung: 安乐礁; bính âm: Ānlè jiāo, Hán-Việt: An Lạc tiêu) là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá này nằm về phía tây nam của đá Bãi Khung và phía đông bắc của đá Tư Nghĩa.", 16),
( 231, "Đá Cô Lin", "", "", "Đá Cô Lin[1] (tiếng Anh: Collins Reef hoặc Johnson North Reef (hay Johnson Reef North); tiếng Trung: 鬼喊礁; bính âm: Guǐhǎn jiāo, Hán-Việt: Quỷ Hám tiêu) là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. ", 16),
( 232, "Đá Đức Hòa", "", "", "Đá Đức Hòa (tiếng Anh: Empire Reef; tiếng Trung: 主权礁; bính âm: Zhǔquán jiāo, Hán-Việt: Chủ Quyền tiêu) là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá nằm gần đầu mút đông bắc của cụm Sinh Tồn, cụ thể là ngay phía tây của đá Ba Đầu và phía đông bắc của đá Bãi Khung.", 16),
( 233, "Đá Gạc Ma", "", "", "Đá Gạc Ma[1] (tiếng Anh: Johnson Reef hoặc Johnson South Reef; tiếng Filipino: Mabini; tiếng Trung: 赤瓜礁; bính âm: Chìguā jiāo, Hán-Việt: Xích Qua tiêu) là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá Gạc Ma là đối tượng tranh chấp giữa Việt Nam, Đài Loan, Philippines và Trung Quốc. ", 16),
( 234, "Đá Ken Nan", "", "", "Đá Ken Nan là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá này nằm về phía tây của đá Tư Nghĩa và cách đảo Sinh Tồn 8 hải lý (14,8 km) về phía đông.[1]", 16),
( 235, "Đá Len Đao", "", "", "Đá Len Đao (tiếng Anh: Lansdowne Reef; tiếng Trung: 琼礁; bính âm: Qióng jiāo, Hán-Việt: Quỳnh tiêu) là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá Len Đao là đối tượng tranh chấp giữa Việt Nam, Đài Loan, Philippines và Trung Quốc. Hiện Việt Nam đang kiểm soát đá Len Đao như một phần của xã Sinh Tồn, huyện Trường Sa, tỉnh Khánh Hòa. ", 16),
( 236, "Đá Nghĩa Hành", "", "", "Đá Nghĩa Hành (tiếng Anh: Loveless Reef; tiếng Trung: 华礁; bính âm: Huá jiāo, Hán-Việt: Hoa tiêu) là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá này nằm ở phía tây nam của đảo Sinh Tồn và cách đá Cô Lin khoảng 4,3 hải lý (8 km) về phía bắc.[1]", 16),
( 237, "Đá Nhạn Gia", "", "", "", 16),
( 238, "Đá Ninh Hòa", "", "", "Đá Ninh Hòa (tiếng Anh: Tetley Reef; tiếng Trung: 扁参礁; bính âm: Biǎnshēn jiāo, Hán-Việt: Biển Sâm tiêu) là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá này nằm về phía tây nam đá Vị Khê và phía đông bắc đá Văn Nguyên.", 16),
( 239, "Đá Phúc Sĩ", "", "", "Đá Phúc Sĩ, có tên cũ là đá Hi Ghen (tiếng Anh: Higgens Reef; tiếng Trung: 屈原礁; bính âm: Qūyuán jiāo, Hán-Việt: Khuất Nguyên tiêu), là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá này nằm giữa đá Văn Nguyên ở phía đông bắc và đá Len Đao ở phía tây nam.", 16),
( 240, "Đá Sơn Hà", "", "", "Đá Sơn Hà (tiếng Anh: Gent Reef; tiếng Trung: 吉阳礁; bính âm: Jíyáng jiāo, Hán-Việt: Cát Dương tiêu) là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá này nằm ở phía tây tây nam đảo Sinh Tồn và phía bắc đá Cô Lin, cách đảo Sinh Tồn khoảng 2,5 km.", 16),
( 241, "Đá Tam Trung", "", "", "Đá Tam Trung[1] là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá này nằm về phía nam đá Nghĩa Hành.", 16),
( 242, "Đá Tư Nghĩa", "", "", "Đá Tư Nghĩa (tên cũ: đá Huy Gơ; tiếng Anh: Hughes Reef hay Hugh Reef; tiếng Trung: 东门礁; bính âm: Dōngmén jiāo, Hán-Việt: Đông Môn tiêu) là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá chỉ nổi khỏi mặt nước khi thủy triều xuống.[1]", 16),
( 243, "Đá Trà Khúc", "", "", "", 16),
( 244, "Đá Văn Nguyên", "", "", "Đá Văn Nguyên (tiếng Anh: Jones Reef; tiếng Trung: 漳溪礁; bính âm: Zhāngxī jiāo, Hán-Việt: Chương Khê tiêu) là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá này nằm về phía tây nam đá Ninh Hòa và phía đông bắc đá Phúc Sĩ.", 16),
( 245, "Đá Vị Khê", "", "", "Đá Vị Khê (tiếng Anh: Bamford Reef; tiếng Trung: 龙虾礁; bính âm: Lóngxiā jiāo, Hán-Việt: Long Hà tiêu) là một rạn san hô thuộc cụm Sinh Tồn của quần đảo Trường Sa. Đá này nằm về phía tây nam của đảo Sinh Tồn Đông và phía đông bắc của đá Ninh Hòa.", 16),
( 246, "Đảo Trường Sa", "", "", "Đảo Trường Sa (tiếng Anh: Spratly Island/Storm Island; tiếng Trung: 南威岛; Hán-Việt: Nam Uy đảo; bính âm: Nánwēi dǎo) là một đảo san hô thuộc cụm Trường Sa của quần đảo Trường Sa. Đảo có diện tích tự nhiên lớn thứ 4 sau Bến Lạc, Thị Tứ và Ba Bình, nằm cách Cam Ranh khoảng 254 hải lý (470,4 km) và cách Vũng Tàu hơn 500 km theo đường biển.[1][2]", 16),
( 247, "Đảo Trường Sa Đông", "", "", "Đảo Trường Sa Đông (tiếng Anh: Central (London) Reef; tiếng Filipino: Gitnang Quezon; tiếng Trung: 中礁; bính âm: Zhōng jiāo, Hán-Việt: Trung tiêu) là một bãi cát nằm trên một rạn san hô thuộc cụm Trường Sa của quần đảo Trường Sa. Đảo cách đá Tây khoảng 6 hải lý (11 km) về phía đông bắc và cách đá Đông khoảng 12,7 hải lý (23,5 km) về phía tây-tây bắc, cách Cam Ranh, Khánh Hòa khoảng 260 hải lý.", 16),
( 248, "Đảo Phan Vinh", "", "", "Đảo Phan Vinh (tiếng Anh: Pearson Reef; tiếng Filipino: Hizon; tiếng Trung: 毕生礁; bính âm: Bìshēng jiāo, Hán-Việt: Tất Sinh tiêu) là phần nổi trên vành san hô của một rạn san hô vòng Pearson (8°57′20″B 113°40′26″Đ / 8,95556°B 113,67389°Đ / 8.95556; 113.67389). Thực thể này thuộc cụm Trường Sa của quần đảo Trường Sa và nằm cách đá Tốc Tan khoảng 14,5 hải lý (27 km) về phía tây bắc.[1] ", 16),
( 249, "Đá Châu Viên", "", "", "Đá Châu Viên là một rạn san hô thuộc cụm Trường Sa của quần đảo Trường Sa. Đá Châu Viên cùng với đá Đông, đá Tây và rạn san hô chứa đảo Trường Sa Đông hợp thành cụm đá ngầm mà các nhà hàng hải quốc tế gọi là London Reefs (cụm rạn Luân Đôn).", 16),
( 250, "Đá Đông", "", "", "Đá Đông (tiếng Anh: East (London) Reef; tiếng Filipino: Silangang Quezon; tiếng Trung: 东礁; bính âm: Dōng jiāo, Hán-Việt: Đông tiêu) là một rạn san hô vòng thuộc cụm Trường Sa của quần đảo Trường Sa. Đá Đông cùng với đá Tây, đá Châu Viên và rạn san hô chứa đảo Trường Sa Đông hợp thành cụm đá ngầm mà các nhà hàng hải quốc tế gọi là London Reefs (cụm rạn Luân Đôn). Đá Đông nằm cách đá Tây khoảng 18 hải lý (33 km) về phía đông và cách đá Châu Viên 10 hải lý (18,5 km) về phía tây.[1] Bản đồ hành chính[2][3] đều thể hiện danh từ riêng là Đông còn danh từ chung để mô tả thực thể là đá. Về bản chất địa lý, đá Đông là một bãi đá san hô, không phải là một đảo.", 16),
( 251, "Đá Lát", "", "", "Đá Lát (tiếng Anh: Ladd Reef; tiếng Trung: 日积礁; bính âm: Rìjī jiāo, Hán-Việt: Nhật Tích tiêu) là một rạn san hô thuộc cụm Trường Sa của quần đảo Trường Sa. Đá Lát là đối tượng tranh chấp giữa Việt Nam, Đài Loan và Trung Quốc. Việt Nam kiểm soát đá này từ ngày 5 tháng 2 năm 1988, quy thuộc nó vào thị trấn Trường Sa, huyện Trường Sa, tỉnh Khánh Hòa, đồng thời duy trì một ngọn hải đăng tại đây.", 16),
( 252, "Đá Núi Cô", "", "", "Đá Núi Cô (tiếng Anh: Cay Marino; tiếng Trung: 玉诺礁; bính âm: Yùnuò jiāo, Hán-Việt: Ngọc Nặc tiêu) là một rạn san hô thuộc cụm Trường Sa của quần đảo Trường Sa. Đá này nằm về phía đông nam của đá Núi Le và phía tây tây bắc của đá Công Đo.", 16),
( 253, "Đá Núi Le", "", "", "Đá Núi Le (tiếng Anh: Cornwallis South Reef; tiếng Filipino: Osmeña; tiếng Trung: 南华礁; bính âm: Nánhuá jiāo, Hán-Việt: Nam Hoa tiêu) là một rạn san hô vòng thuộc cụm Trường Sa của quần đảo Trường Sa. Đá Núi Le cách đảo Trường Sa 134 hải lý (248 km) về phía đông, cách đá Tiên Nữ 27 hải lý (50 km) về phía tây-tây nam.", 16),
( 254, "Đá Núi Mon", "", "", "Đá Núi Mon[1][2] là một rạn san hô thuộc cụm Trường Sa của quần đảo Trường Sa. Đá này nằm về phía bắc của đảo Phan Vinh A khoảng 14 hải lý (26,1 km).[3]", 16),
( 255, "Đá Tây", "", "", "Đá Tây (tiếng Anh: West (London) Reef; tiếng Filipino: Kanlurang Quezon; tiếng Trung: 西礁; bính âm: Xī jiāo, Hán-Việt: Tây tiêu) là một rạn san hô vòng thuộc cụm Trường Sa của quần đảo Trường Sa. Đá Tây cùng với đá Đông, đá Châu Viên và rạn san hô chứa đảo Trường Sa Đông hợp thành cụm đá ngầm mà các nhà hàng hải quốc tế gọi là cụm rạn Luân Đôn (London Reefs). Đá Tây nằm cách đảo Trường Sa 19,5 hải lý (36 km) về phía đông bắc.[1]", 16),
( 256, "Đá Tiên Nữ", "", "", "Đá Tiên Nữ (tiếng Anh: Tennent Reef (hải đồ của Anh) hoặc Pigeon Reef (hải đồ của Mỹ); tiếng Filipino: Lopez-Jaena; tiếng Trung: 无乜礁; bính âm: Wúmiē jiāo, Hán-Việt: Vô Khiết tiêu) là một rạn san hô vòng thuộc cụm Trường Sa của quần đảo Trường Sa. Đá này là đối tượng tranh chấp giữa Việt Nam, Đài Loan, Philippines và Trung Quốc. Hiện Việt Nam đang kiểm soát rạn vòng này như một phần của thị trấn Trường Sa, huyện Trường Sa, tỉnh Khánh Hòa, đồng thời duy trì một hải đăng tại đây.", 16),
( 257, "Đá Tốc Tan", "", "", "Đá Tốc Tan (tiếng Anh: Alison Reef; tiếng Filipino: De Jesus; tiếng Trung: 六门礁; bính âm: Liùmén jiāo, Hán-Việt: Lục Môn tiêu) là một rạn san hô vòng thuộc cụm Trường Sa của quần đảo Trường Sa. Đá Tốc Tan cách đảo Phan Vinh 14,6 hải lý (27 km) về phía đông nam và cách đá Núi Le 6 hải lý (11 km) về phía tây bắc.", 16),
( 258, "Bãi ngầm Chim Biển", "", "", "Bãi ngầm Chim Biển[1] là một bãi ngầm thuộc cụm Trường Sa của quần đảo Trường Sa. Trên bản đồ, bãi này được thể hiện tại một vị trí ở phía đông bắc của đá Ba Kè (thuộc bãi ngầm Vũng Mây) và phía nam của đảo Trường Sa. Phần lớn diện tích bãi này nằm ở bên trái kinh tuyến 112° Đông.", 16),
( 259, "Bãi ngầm Mỹ Hải", "", "", "Bãi ngầm Mỹ Hải[1] (còn có tên là bãi Ngọc Điền, tiếng Anh: Jubilee Bank hay Jubilee Seamount; tiếng Trung: 朱应滩; bính âm: Zhūyìng tān, Hán-Việt: Chu Ứng than) là một bãi ngầm thuộc cụm Trường Sa của quần đảo Trường Sa. Bãi này nằm về phía tây nam của đá Lát, sâu khoảng 278 m.[2]", 16),
( 260, "Bãi ngầm Nguyệt Sương/Xương", "", "", "Bãi ngầm Nguyệt Sương hay bãi ngầm Nguyệt Xương[1] (tiếng Anh: Dhaulle Shoal, có nơi ghi Duvalle Shoal; tiếng Trung: 逍遥暗沙; bính âm: Xiāoyáo ànshā, Hán-Việt: Tiêu Dao ám sa) là một bãi ngầm thuộc cụm Trường Sa của quần đảo Trường Sa. Nằm về phía tây đá Chữ Thập, bãi ngầm này được ghi nhận vào năm 1826.[2]", 16),
( 261, "Đảo An Bang", "", "", "Đảo An Bang (tiếng Anh: Amboyna Cay; tiếng Filipino: Calantiyaw; tiếng Mã Lai: Pulau Amboyna Kecil; tiếng Trung: 安波沙洲; bính âm: Ānbō shāzhōu, Hán-Việt: An Ba sa châu) là một cồn cát thuộc cụm An Bang (tên cũ là cụm Thám Hiểm) của quần đảo Trường Sa. Đảo nằm cách đảo Trường Sa Lớn 75 hải lý về phía Đông Nam, cách bãi Thuyền Chài hơn 20 hải lý về phía Tây Nam. Tọa độ địa lí ghi trên bia chủ quyền đảo An Bang là 7°52′0″B 112°54′30″Đ / 7,86667°B 112,90833°Đ / 7.86667; 112.90833.", 16),
( 262, "Đá Công Đo", "", "", "Đá Công Đo[1] là một rạn san hô vòng thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa. Đá này nằm cách đá Tiên Nữ 41,3 hải lý (76,5 km) về phía đông nam.[2]", 16),
( 263, "Đá Én Ca", "", "", "Đá Én Ca[1] (tiếng Anh: Erica Reef; tiếng Filipino: Gabriela Silang; tiếng Mã Lai: Terumbu Siput; tiếng Trung: 簸箕礁; bính âm: Bòji jiāo; Hán-Việt: Bá Ky tiêu.) là một rạn san hô vòng thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa.", 16),
( 264, "Đá Hoa Lau", "", "", "Đá Hoa Lau là một rạn san hô vòng thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa. Đá này nằm cách đảo An Bang khoảng 60,4 hải lý (111,8 km) về phía đông nam.[1]", 16),
( 265, "Đá Kỳ Vân", "", "", "Đá Kỳ Vân[1] (tiếng Anh: Mariveles Reef; tiếng Mã Lai: Terumbu Mantanani; tiếng Trung: 南海礁; bính âm: Nánhǎi jiāo; Hán-Việt: Nam Hải tiêu) là một rạn san hô vòng thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa. Đá này nằm cách đá Thuyền Chài 35 hải lý (64,8 km) về phía đông nam.[2]", 16),
( 266, "Bãi Kiêu Ngựa và đá Kiêu Ngựa", "", "", "Kiêu Ngựa[Ghi chú 1] là tên gọi chung cho một hệ thống san hô ngầm (bãi) và một rạn san hô vòng (đá) thuộc hệ thống san hô ngầm đó. Cả hai thực thể đều thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa. Bãi Kiêu Ngựa nằm cách bãi Thám Hiểm 10 hải lý (18,5 km) về phía tây nam[1] còn đá Kiêu Ngựa nằm ở cực tây nam của bãi Kiêu Ngựa.", 16),
( 267, "Đá Sác Lốt", "", "", "Đá Sác Lốt[1] là một rạn san hô thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa. Đá này nằm cách đá Hoa Lau 29 hải lý (53,7 km) về phía nam-tây nam.[2]", 16),
( 268, "Đá Suối Cát", "", "", "Đá Suối Cát[1] là một rạn san hô vòng thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa.", 16),
( 269, "Đá Thanh Kỳ", "", "", "Đá Thanh Kỳ (tiếng Anh: Ardasier Breakers; tiếng Trung: 息波礁; bính âm: Xībō jiāo, Hán-Việt: Tức Ba tiêu) là một rạn san hô thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa. Đá này nằm về phía đông của đá Kỳ Vân và phía bắc của bãi Kiêu Ngựa.", 16),
( 270, "Đá/bãi Thuyền Chài", "", "", "Đá Thuyền Chài[1] (hay bãi Thuyền Chài; tiếng Anh: Barque Canada Reef; tiếng Filipino: Magsaysay; tiếng Mã Lai: Terumbu Perahu; tiếng Trung: 柏礁; bính âm: Bǎi jiāo, Hán-Việt: Bách tiêu) là một rạn san hô vòng (không phải đảo) thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa.", 16),
( 271, "Bãi Phù Mỹ", "", "", "Bãi Phù Mỹ[1] là một rạn san hô vòng thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa. Rạn vòng này nằm cách bãi Trăng Khuyết 17,7 hải lý (32,8 km) về phía đông bắc.[2]", 16),
( 272, "Bãi Thám Hiểm", "", "", "Bãi Thám Hiểm (bãi Thám Hiểm: tiếng Anh: Investigator Shoal; tiếng Filipino: Pawikan; tiếng Mã Lai: Terumbu Peninjau; tiếng Trung: 榆亚暗沙; bính âm: Yúyà ànshā; Hán-Việt: Du Á ám sa) là một rạn san hô vòng lớn thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa.", 16),
( 273, "Bãi Trăng Khuyết", "", "", "Bãi Trăng Khuyết là một rạn san hô vòng thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa. Rạn vòng này nằm cách đô thị Rizal trên đảo Palawan của Philippines 71 hải lý (132 km) về phía tây.[1]", 16),
( 274, "Bãi ngầm Ngũ Phụng", "", "", "Bãi Ngũ Phụng (tiếng Anh: Northeast Shea hay Northeast Shoal; tiếng Trung: 校尉暗沙, bính âm: Xiaowei Ansha) là một bãi ngầm thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa. Tọa độ của bãi ngầm này là 8°310 N, 115°150.[1] Bãi ngầm này nằm về phía bắc Đá Công Đo (do Philippines kiểm soát) khoảng 34 km và nằm về phía đông nam của Đá Tiên Nữ (do Việt Nam kiểm soát) khoảng 72 km.", 16),
( 275, "Bãi ngầm Tam Thanh", "", "", "Bãi ngầm Tam Thanh[1] (tiếng Anh: Glasgow Bank; tiếng Trung: 南乐暗沙; bính âm: Nánlè ànshā, Hán-Việt: Nam Nhạc ám sa) là một bãi ngầm thuộc cụm An Bang của quần đảo Trường Sa. Theo Findlay (1878), bãi trải dài khoảng 3 hải lý (5,6 km) và cấu thành từ cát và chỏm đá - vài chỗ nhô cao 6,4 - 9,8 m so với mặt biển.[2] Bãi này nằm về phía đông bắc đá Công Đo.", 16),
( 276, "Bãi ngầm Khánh Hội", "", "", "Bãi Khánh Hội (tiếng Anh: Director Shoal, tiếng Trung: 指向礁, bính âm: Zhǐxiàng jiāo) là một bãi đá ngầm thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa, nằm vế phía tây nam của bãi Trăng Khuyết khoảng 58 km  và nằm về phía đông của đá Công Đo khoảng 77 km.", 16),
( 277, "Đảo Bình Nguyên", "", "", "Bình Nguyên là một đảo cát nhỏ thuộc cụm Bình Nguyên của quần đảo Trường Sa. Đảo này nằm cách đảo Vĩnh Viễn khoảng 9 km về phía bắc-đông bắc.", 16),
( 278, "Đảo Vĩnh Viễn", "", "", "Đảo Vĩnh Viễn là một đảo san hô thuộc cụm Bình Nguyên của quần đảo Trường Sa. Đảo này nằm về phía bắc của bãi Hải Sâm và cách đảo Bình Nguyên khoảng 9 km về phía nam-tây nam.", 16),
( 279, "Đá Bồ Đề", "", "", "Đá Bồ Đề[1] (tiếng Anh: chưa rõ; tiếng Trung: 片礁; bính âm: Piàn jiāo, Hán-Việt: Phiến tiêu) là một rạn san hô thuộc cụm Bình Nguyên của quần đảo Trường Sa. Đá này nằm về phía đông nam của đá Long Điền, phía tây bắc của bãi Cái Mép và phía nam của bãi Sa Bin. Tọa độ của đá này là 9°31′0″B 116°23′30″Đ.", 16),
( 280, "Đá Cỏ My", "", "", "", 16),
( 281, "Đá Ba Cờ", "", "", "Đá Ba Cờ[1] là một rạn san hô thuộc cụm Bình Nguyên của quần đảo Trường Sa. Đá này nằm về phía đông của đảo Vĩnh Viễn và cách đá Khúc Giác 3,8 hải lý (7 km) về phía bắc.[2]", 16),
( 282, "Đá Chà Và", "", "", "Đá Chà Và[1] (tiếng Anh: Foulerton Reef; tiếng Trung: 东华礁; bính âm: Dōnghuá jiāo; Hán-Việt: Đông Hoa tiêu) là một rạn san hô thuộc cụm Bình Nguyên của quần đảo Trường Sa. Đá này nằm ở cực đông của bãi Nam và sâu gần 5,5 m.[2]", 16),
( 283, "Đá Gò Già", "", "", "Đá Gò Già[1] là một rạn san hô thuộc cụm Bình Nguyên, quần đảo Trường Sa.", 16),
( 284, "Đá Hợp Kim", "", "", "Đá Hợp Kim[1] là một rạn san hô thuộc cụm Bình Nguyên, quần đảo Trường Sa. Đá này nằm cách đảo Bình Nguyên 15,9 hải lý (29,4 km) về phía đông, cách đá Ba Cờ và đá Khúc Giác lần lượt là 6,7 và 10,3 hải lý (12,4 và 19 km) về phía bắc tây bắc.[2]", 16),
( 285, "Đá Khúc Giác", "", "", "Đá Khúc Giác[1] là một rạn san hô thuộc cụm Bình Nguyên của quần đảo Trường Sa. Đá này nằm về phía đông - đông nam của đảo Vĩnh Viễn và về phía đông - đông bắc của bãi Hải Sâm.", 16),
( 286, "Đá Long Điền", "", "", "Đá Long Điền[1] là một rạn san hô thuộc cụm Bình Nguyên của quần đảo Trường Sa. Đá này nằm cách bãi Sa Bin 18 hải lý (33,3 km) về phía tây nam.[2]", 16),
( 287, "Đá Long Hải", "", "", "Đá Long Hải[1] là một rạn san hô vòng thuộc cụm Bình Nguyên của quần đảo Trường Sa. Đá này nằm về phía đông bắc của cụm Sinh Tồn, phía đông của cụm Nam Yết và phía tây nam của đảo Vĩnh Viễn.", 16),
( 288, "Đá Lục Giang", "", "", "Đá Lục Giang[1] là một rạn san hô thuộc cụm Bình Nguyên của quần đảo Trường Sa. Đá này nằm cách đá Long Hải 3 hải lý (5,6 km) về phía đông bắc.[2]", 16),
( 289, "Đá Mỏ Vịt", "", "", "Đá Mỏ Vịt[1] (tiếng Anh: Hirane Shoal;[2] tiếng Trung: 安塘礁; bính âm: Āntáng jiāo; Hán-Việt: An Đường tiêu) là một rạn san hô thuộc cụm Bình Nguyên của quần đảo Trường Sa. Bãi này nằm cách đá Ba Cờ 18 hải lý (33,3 km) về phía đông bắc và có độ sâu dưới 1,8 m.[3]", 16),
( 290, "Đá Phật Tự", "", "", "Đá Phật Tự[1] là một rạn san hô thuộc cụm Bình Nguyên của quần đảo Trường Sa. Đá này cách bãi Hải Sâm 29,3 hải lý (54,3 km) về phía đông nam.[2]", 16),
( 291, "Đá Suối Ngọc", "", "", "Đá Suối Ngọc là một rạn san hô vòng thuộc cụm Bình Nguyên của quần đảo Trường Sa, cách đá Vành Khăn 28,3 hải lý (52,4 km) về phía nam.[1]", 16),
( 292, "Đá Tây Nam", "", "", "Đá Tây Nam[1] hay còn gọi là bãi Tây Nam[2] (tiếng Anh: Pennsylvania South Reef; tiếng Trung: 东坡礁; bính âm: Dōngpō jiāo; Hán-Việt: Đông Pha tiêu) là một rạn san hô thuộc cụm Bình Nguyên của quần đảo Trường Sa. Đá này nằm về phía đông nam của đá Khúc Giác và phía đông bắc của đá Phật Tự.", 16),
( 293, "Đá Trung Lễ", "", "", "", 16),
( 294, "Đá Vành Khăn", "", "", "Đá Vành Khăn là một rạn san hô vòng thuộc cụm Bình Nguyên của quần đảo Trường Sa. Đá này nằm cách đảo Sinh Tồn Đông 57 hải lý (105,6 km) về phía đông và cách đảo Vĩnh Viễn 51 hải lý (94,5 km) về phía nam.[1]", 16),
( 295, "Đá Vĩnh Hợp", "", "", "", 16),
( 296, "Đá Vĩnh Tường", "", "", "Đá Vĩnh Tường (tiếng Anh: chưa rõ; tiếng Trung: 碎浪暗沙, bính âm: Suilang Ansha)[1] là một bãi ngầm thuộc cụm An Bang (cụm Thám Hiểm) của quần đảo Trường Sa, cách đá Kiêu Ngựa khoảng 90 km theo hướng tây bắc, nằm về hướng đông của đá hoa Lau khoảng 113 km, và về phía đông bắc của đá Sác Lốt khoảng 143 km, bãi Viper khoảng 41 km. Tọa độ của Đá bãi ngầm này là 7° 11 N, 114° 49 E.[2]", 16),
( 297, "Bãi Cái Mép", "", "", "Bãi Cái Mép[1] là một rạn san hô vòng thuộc cụm Bình Nguyên của quần đảo Trường Sa.", 16),
( 298, "Bãi Cỏ Mây", "", "", "Bãi Cỏ Mây là một rạn san hô vòng thuộc cụm Bình Nguyên của quần đảo Trường Sa. Rạn vòng này nằm về phía đông nam của đá Vành Khăn và cách bãi Sa Bin 35 hải lý (64,8 km) về phía tây.[1]", 16),
( 299, "Bãi Cỏ Rong", "", "", "", 16),
( 300, "Bãi Đá Bắc", "", "", "Cụm Đá Bắc[1] hay bãi Đá Bắc[2] là một vùng rạn san hô thuộc cụm Bình Nguyên của quần đảo Trường Sa. Theo Trần Công Trục (2012), khu vực cụm Đá Bắc gồm đá Cỏ My và đá Gò Già.[1] Vùng này nằm về phía đông cụm Hồ Tràm và ở cực nam của bãi Cỏ Rong.", 16),
( 301, "Bãi Đồ Bàn", "", "", "Bãi Đồ Bàn là một bãi ngầm thuộc cụm Bình Nguyên của quần đảo Trường Sa.", 16),
( 302, "Bãi Đồi Mồi", "", "", "Bãi Đồi Mồi[1] là một rạn san hô vòng thuộc cụm Bình Nguyên của quần đảo Trường Sa. Rạn vòng này nằm cách bãi Cái Mép 28,1 hải lý (52 km) về phía tây nam[2] và cách bãi Phù Mỹ 12,9 hải lý (23,9 km) về phía đông nam.[3]", 16),
( 303, "Bãi Đồng Cam", "", "", "Bãi Đồng Cam (tiếng Anh: Third Thomas Shoal; tiếng Trung: 和平暗沙; bính âm: Hépíng ànshā, Hán-Việt: Hoà Bình ám sa) là một rạn san hô thuộc cụm Bình Nguyên của quần đảo Trường Sa. Rạn này nằm về phía đông bắc của đảo Bình Nguyên cách khoảng 7.5 hải lý. Bãi này trải rộng khoảng 3-4 hải lý.[1]", 16),
( 304, "Bãi Đồng Giữa", "", "", "Bãi Đồng Giữa là một bãi ngầm thuộc cụm Bình Nguyên của quần đảo Trường Sa.", 16),
( 305, "Bãi Đồng Thạnh", "", "", "Đá Đồng Thạnh hay đá Đồng Thanh[1] (tiếng Anh: Marie Louise Bank; tiếng Trung: 雄南礁; bính âm: Xióngnán jiāo; Hán-Việt: Hùng Nam tiêu) là một rạn đá ngầm thuộc cụm Bình Nguyên của quần đảo Trường Sa. Đá này tiếp giáp phía bắc của bãi Cỏ Rong và sâu 27 m.[2]", 16),
( 306, "Bãi Hải Sâm", "", "", "Ảnh vệ tinh chụp bãi Hải Sâm (NASA)", 16),
( 307, "Bãi Hải Yến", "", "", "Bãi Hải Yến (tiếng Anh: chưa rõ; tiếng Trung: 彬礁, bính âm: Bin Jiao) là một bãi ngầm nằm về phía đông của đá Chà Và, của Bãi cạn Nam thuộc cụm Bình Nguyên của quần đảo Trường Sa.", 16),
( 308, "Bãi Hữu Độ", "", "", "Bãi Hữu Độ (tiếng Anh: Sandy Shoal; tiếng Filipino: Mabuhangin; tiếng Trung: 神仙暗沙; bính âm: Shénxiān ànshā, Hán-Việt: Thần Tiên ám sa) là một bãi ngầm nhỏ và dốc thuộc cụm Bình Nguyên của quần đảo Trường Sa. Bãi này nằm về phía đông của bãi Rạch Vang và bãi Vĩnh Tuy, cách bãi Vĩnh Tuy khoảng 9 hải lý (16,7 km).[1]", 16),
( 309, "Bãi Na Khoai", "", "", "Bãi Na Khoai[1] là một bãi ngầm thuộc cụm Bình Nguyên của quần đảo Trường Sa.", 16),
( 310, "Bãi Nam", "", "", "Bãi (cạn) Nam[1] là một bãi cạn/bãi ngầm thuộc cụm Bình Nguyên của quần đảo Trường Sa. Bãi này nằm về phía nam đá Gò Già. Nằm ở đầu phía đông bắc của cụm bãi cạn Nam có một rạn san hô là đá Chà Và, và ở phần tây nam của bãi này là một rạn san hô khác là đá Tây Nam..[1] Ngoài ra còn có bãi Hải Yến về phía đông bắc của đá Chà Và.[2]", 16),
( 311, "Bãi Ôn Thuỷ", "", "", "Bãi Ôn Thủy là một bãi ngầm thuộc cụm Bình Nguyên của quần đảo Trường Sa. Vị trí của bãi này chưa được xác định rõ ràng, nhưng nó nằm giữa bãi Thạch Sa và bãi Na Khoai.[1]", 16),
( 312, "Bãi Rạch Lấp", "", "", "Bãi Rạch Lấp[1] là một bãi nông thuộc cụm Bình Nguyên của quần đảo Trường Sa.", 16),
( 313, "Bãi Rạch Vang", "", "", "Bãi Rạch Vang[1] là một bãi ngầm thuộc cụm Bình Nguyên của quần đảo Trường Sa.", 16),
( 314, "Bãi Sa Bin", "", "", "Bãi Sa Bin[1] là một rạn san hô vòng thuộc cụm Bình Nguyên của quần đảo Trường Sa.", 16),
( 315, "Bãi Suối Ngà", "", "", "Bãi Suối Ngà[1] là một rạn san hô vòng thuộc cụm Bình Nguyên của quần đảo Trường Sa. Rạn vòng này nằm cách đá Suối Ngọc 26 hải lý (48,2 km) về phía đông.[2]", 16),
( 316, "Bãi Thạch Sa", "", "", "Bãi Thạch Sa là một rạn san hô vòng chìm ngập dưới nước thuộc cụm Bình Nguyên của quần đảo Trường Sa.", 16),
( 317, "Bãi Tổ Muỗi", "", "", "Bãi Tổ Muỗi[1] là một bãi ngầm thuộc cụm Bình Nguyên của quần đảo Trường Sa. Thực thể này tách biệt khỏi bãi Cỏ Rong do có một vùng nước rộng 12 hải lý (22,2 km) và sâu 1.200 m ngăn cách bãi Tổ Muỗi với phần tây bắc của bãi Cỏ Rong.[2]", 16),
( 318, "Bãi Vĩnh Tuy", "", "", "Bãi Vĩnh Tuy là một bãi ngầm thuộc cụm Bình Nguyên của quần đảo Trường Sa. Bãi này nằm cách bãi Rạch Vang khoảng 6 hải lý (11,1 km) về phía đông.[1]", 16),
( 319, "Bãi Cảnh Dương", "", "", "", 16),
( 320, "Bãi Đông Sơn", "", "", "", 16),
( 321, "Bãi Huyền Trân", "", "", "Bãi Huyền Trân hay bãi cạn Huyền Trân, bãi ngầm Huyền Trân (tiếng Anh: Alexandra Bank; tiếng Trung: 人骏滩; bính âm: Rénjùn tān, Hán-Việt: Nhân Tuấn than) là một rạn san hô ở phía nam Biển Đông. Việt Nam cho xây dựng tại đây cấu trúc thép có tên là nhà giàn DK1 và giao cho Tiểu đoàn DK1 trực thuộc Bộ Tư lệnh Vùng 2 Hải quân kiểm soát, đồng thời duy trì một trạm khí tượng và một hải đăng.", 16),
( 322, "Bãi Phúc Nguyên", "", "", "Bãi Phúc Nguyên hay bãi cạn Phúc Nguyên, bãi ngầm Phúc Nguyên (tiếng Anh: Prince Consort Bank; tiếng Trung: 西卫滩; bính âm: Xīwèi tān, Hán-Việt: Tây Vệ than) là một cụm rạn san hô ở phía nam Biển Đông. Tại đây Việt Nam cho lắp đặt cấu trúc thép có tên là nhà giàn DK1 và giao cho Tiểu đoàn DK1 trực thuộc Bộ Tư lệnh Vùng 2 Hải quân kiểm soát.", 16),
( 323, "Bãi Phúc Tần", "", "", "Bãi Phúc Tần hay bãi cạn Phúc Tần, bãi ngầm Phúc Tần (tiếng Anh: Prince of Wales Bank; tiếng Trung: 广雅滩; bính âm: Guǎngyǎ tān, Hán-Việt: Quảng Nhã than) là một rạn san hô vòng ở phía nam Biển Đông. Tại đây Việt Nam cho lắp đặt các cấu trúc thép có tên là nhà giàn DK1 và giao cho Tiểu đoàn DK1 trực thuộc Bộ Tư lệnh Vùng 2 Hải quân kiểm soát, đồng thời duy trì hải đăng.", 16),
( 324, "Bãi Quế Đường", "", "", "Bãi Quế Đường hay bãi cạn Quế Đường, bãi ngầm Quế Đường (tiếng Anh: Grainger Bank; tiếng Trung: 李准滩; bính âm: Lǐzhǔn tān, Hán-Việt: Lý Chuẩn than) là một rạn san hô ở phía nam Biển Đông. Việt Nam cho xây dựng tại đây cấu trúc thép có tên là nhà giàn DK1 do Tiểu đoàn DK1 trực thuộc Bộ Tư lệnh Vùng 2 Hải quân kiểm soát, đồng thời duy trì một hải đăng.", 16),
( 325, "Bãi Thanh Long", "", "", "", 16),
( 326, "Bãi Tư Chính", "", "", "Bãi Tư Chính hay bãi cạn Tư Chính, bãi ngầm Tư Chính (tiếng Anh: Vanguard Bank; tiếng Trung: 万安滩; bính âm: Wànān tān, Hán-Việt: Vạn An than) là một cụm rạn san hô ở phía nam Biển Đông. Đây là thềm lục địa của việt nam.", 16),
( 327, "Bãi Vũng Mây", "", "", "Bãi Vũng Mây hay bãi cạn Vũng Mây, bãi ngầm Vũng Mây (tiếng Anh: Rifleman Bank; tiếng Trung: 南薇滩; bính âm: Nánwēi tān, Hán-Việt: Nam Vi than) là một rạn san hô vòng ở phía nam Biển Đông. Việt Nam cho lắp đặt tại đây các cấu trúc thép có tên là nhà giàn DK1 và giao cho Tiểu đoàn DK1 trực thuộc Bộ Tư lệnh Vùng 2 Hải quân kiểm soát, đồng thời duy trì một hải đăng.", 16),
( 328, "Bãi Cà Mau", "", "", "Bãi Cà Mau (hay bãi cạn Cà Mau) là một bãi ngầm trong vịnh Thái Lan, nằm về phía tây nam mũi Cà Mau. Tại đây Việt Nam cho lắp đặt cấu trúc thép có tên là nhà giàn DK1 và giao cho Tiểu đoàn DK1 trực thuộc Bộ Tư lệnh Vùng 2 Hải quân kiểm soát.", 16),
( 329, "Đảo Biện Sơn", "19°19′17″B", "105°49′12″Đ", "Đảo Biện Sơn hay còn gọi là hòn Biện Sơn, đảo Nghi Sơn là một đảo sát bờ biển ở thị xã Nghi Sơn tỉnh Thanh Hóa, Việt Nam.[1][2][3]", 5),
( 330, "Hòn Nẹ", "19°54′45″B", "106°00′30″Đ", "Hòn Nẹ là tên chỉ hòn đảo nhỏ nằm ngoài khơi vịnh Bắc Bộ, Biển Đông. Đảo Nẹ nằm thuộc hải phận tỉnh Thanh Hóa, nó nằm cách đất liền huyện Hậu Lộc khoảng 6 km về phía Đông, cách bờ biển Hoằng Hoá khoảng 5 km về phía Đông Bắc và cách bờ biển Nga Sơn khoảng 6 km về phía Nam. Hòn Nẹ nằm ở tọa độ 19°5446 độ Vĩ bắc và 106°0032 độ Kinh đông.", 5),
( 331, "Hòn Mê", "19°22′20″B", "105°55′37″Đ", "Hòn Mê là quần đảo trong Vịnh Bắc Bộ thuộc vùng đất tỉnh Thanh Hóa, Việt Nam. Về hành chính quần đảo hiện thuộc phường Hải Bình thị xã Nghi Sơn tỉnh Thanh Hóa.[1][2]", 5),
( 332, "Hòn Vàng", "19°22′05″B", "105°54′31″Đ", "", 5),
( 333, "Hòn Vát", "19°22′00″B", "105°54′42″Đ", "", 5),
( 334, "Hòn Bảng", "19°21′26″B", "105°52′25″Đ", "", 5),
( 335, "Hòn Hộp", "19°21′10″B", "105°52′40″Đ", "", 5),
( 336, "Hòn Đót", "19°21′07″B", "105°55′56″Đ", "", 5),
( 337, "Hòn Miêng", "19°20′40″B", "105°54′03″Đ", "", 5),
( 338, "Hòn Sô", "19°20′05″B", "105°53′23″Đ", "", 5),
( 339, "Hòn Sập", "19°19′29″B", "105°53′52″Đ", "", 5),
( 340, "Hòn Nếu", "19°19′08″B", "105°54′35″Đ", "", 5),
( 341, "Đảo Lan Châu", "18°49′14″B", "105°43′21″Đ", "", 6),
( 342, "Hòn Ngư", "18°48′05″B", "105°46′43″Đ", "", 6),
( 343, "Cồn Khơi", "18°50′34″B", "105°45′44″Đ", "", 6),
( 344, "Cồn Lộng", "18°49′55″B", "105°43′34″Đ", "", 6),
( 345, "Hòn Mắt", "18°47′48″B", "105°57′40″Đ", "", 6),
( 346, "Hòn Mắt Con", "18°47′38″B", "105°58′49″Đ", "", 6),
( 347, "Đảo Sơn Dương", "18°06′09″B", "106°27′34″Đ", "Đảo Sơn Dương hay Hòn Sơn Dương là là một hòn đảo nhỏ thuộc xã Kỳ Lợi, thị xã Kỳ Anh, tỉnh Hà Tĩnh, Việt Nam.", 7),
( 348, "Hòn Hải Đăng", "18°18′34″B", "106°09′53″Đ", "", 7),
( 349, "Hòn Lạp", "18°46′05″B", "105°49′51″Đ", "", 7),
( 350, "Hòn Nồm", "18°44′49″B", "105°50′31″Đ", "", 7),
( 351, "Hòn Môồng", "18°18′30″B", "106°10′10″Đ", "", 7),
( 352, "Hòn Oản", "18°16′50″B", "106°07′00″Đ", "", 7),
( 353, "Hòn Chim", "18°06′59″B", "106°29′21″Đ", "", 7),
( 354, "Cồn Voi", "17°59′51″B", "106°28′19″Đ", "", 7),
( 355, "Hòn Cỏ", "17°56′34″B", "106°31′22″Đ", "", 8),
( 356, "Hòn La", "17°56′07″B", "106°31′56″Đ", "", 8),
( 357, "Hòn Ông", "17°54′46″B", "106°40′21″Đ", "", 8),
( 358, "Hòn Vũng Chùa", "17°54′37″B", "106°29′42″Đ", "Vũng Chùa – Đảo Yến là một địa điểm du lịch sinh thái, hấp dẫn khách du lịch đến khám phá bởi vẻ đẹp hoang sơ, bãi biển trong sạch và vị thế địa lý đặc biệt. Đây là nơi an táng Đại tướng Võ Nguyên Giáp.[1]", 8),
( 359, "Hòn Sước", "17°52′38″B", "106°28′12″Đ", "", 8),
( 360, "Quần đảo Cù lao Chàm", "15°56′55″B", "108°31′24″Đ", "Cù lao Chàm là một cụm đảo, về mặt hành chính trực thuộc xã đảo Tân Hiệp, thành phố Hội An, tỉnh Quảng Nam, nằm cách bờ biển Cửa Đại 16 km và đã được UNESCO công nhận là khu dự trữ sinh quyển thế giới.[1][2]", 12),
( 361, "Hòn Cô", "15°58′23″B", "108°25′16″Đ", "", 12),
( 362, "Hòn Cu", "15°58′22″B", "108°24′56″Đ", "", 12),
( 363, "Hòn Lá", "15°58′22″B", "108°26′49″Đ", "", 12),
( 364, "Hòn Nhàn", "15°58′07″B", "108°30′38″Đ", "", 12),
( 365, "Hòn Giai", "15°56′32″B", "108°28′47″Đ", "", 12),
( 366, "Hòn Mồ", "15°55′53″B", "108°28′25″Đ", "", 12),
( 367, "Hòn Tai", "15°54′25″B", "108°32′08″Đ", "", 12),
( 368, "Hòn Ông", "15°48′49″B", "108°41′32″Đ", "", 12),
( 369, "Hòn Dừa", "15°30′02″B", "108°41′16″Đ", "", 12),
( 370, "Đảo Lý Sơn", "15°22′40″B", "109°07′13″Đ", "Lý Sơn là một huyện đảo thuộc tỉnh Quảng Ngãi, Việt Nam.", 13),
( 371, "Cù lao Bờ Bãi", "15°25′41″B", "109°04′58″Đ", "", 13),
( 372, "Hòn Ông", "15°23′33″B", "108°46′12″Đ", "", 13),
( 373, "Hòn Lũy", "15°23′32″B", "108°46′53″Đ", "", 13),
( 374, "Hòn Đình", "15°23′25″B", "108°46′41″Đ", "", 13),
( 375, "Hòn Trà", "15°23′20″B", "108°46′28″Đ", "", 13),
( 376, "Hòn Bà", "15°23′15″B", "108°46′27″Đ", "Hòn Bà tại Việt Nam có thể là:", 13),
( 377, "Hòn Ông", "15°15′12″B", "108°55′51″Đ", "", 13),
( 378, "Hòn Ao", "15°14′59″B", "108°56′09″Đ", "", 13),
( 379, "Hòn Bồng Than", "15°11′35″B", "108°57′10″Đ", "", 13),
( 380, "Hòn Con Rùa", "14°21′44″B", "109°11′08″Đ", "", 14),
( 381, "Hòn Nhàn", "14°15′07″B", "109°12′27″Đ", "", 14),
( 382, "Hòn Tranh", "14°13′56″B", "109°11′59″Đ", "", 14),
( 383, "Hòn Con Trâu", "14°08′17″B", "109°17′31″Đ", "", 14),
( 384, "Hòn Dựng", "13°57′52″B", "109°15′25″Đ", "", 14),
( 385, "Hòn Ông Cơ", "13°54′06″B", "109°18′57″Đ", "", 14),
( 386, "Hòn Ông Căn", "13°54′02″B", "109°20′59″Đ", "", 14),
( 387, "Hòn Cân", "13°53′53″B", "109°20′44″Đ", "", 14),
( 388, "Hòn Nghiêm Kinh Chiểu", "13°52′49″B", "109°18′05″Đ", "", 14),
( 389, "Hòn Khô", "13°45′50″B", "109°17′51″Đ", "", 14),
( 390, "Hòn Ngang", "13°41′02″B", "109°14′16″Đ", "", 14),
( 391, "Hòn Đất", "13°40′51″B", "109°15′03″Đ", "", 14),
( 392, "Hòn Rớ", "13°40′06″B", "109°14′15″Đ", "", 15),
( 393, "Cù lao Xanh", "13°37′03″B", "109°20′51″Đ", "", 15),
( 394, "Hòn Chớp Tròn", "13°35′37″B", "109°22′05″Đ", "", 15),
( 395, "Hòn Khô", "13°34′45″B", "109°17′06″Đ", "", 15),
( 396, "Cù lao Ông Xá", "13°23′47″B", "109°14′31″Đ", "", 15),
( 397, "Hòn Yến", "13°22′52″B", "109°16′45″Đ", "", 15),
( 398, "Cù lao Mái Nhà", "13°16′50″B", "109°19′58″Đ", "", 15),
( 399, "Hòn Yến", "13°13′36″B", "109°18′25″Đ", "", 15),
( 400, "Hòn Chùa", "13°10′37″B", "109°18′33″Đ", "", 15),
( 401, "Hòn Than", "13°10′20″B", "109°19′06″Đ", "", 15),
( 402, "Hòn Dừa", "13°10′08″B", "109°19′15″Đ", "", 15),
( 403, "Hòn Cồ", "12°58′17″B", "109°26′21″Đ", "", 15),
( 404, "Hòn Một", "13°28′52″B", "109°14′52″Đ", "", 15),
( 405, "Nhất Tự Sơn", "13°25′11″B", "109°13′38″Đ", "", 15),
( 406, "Hòn Nưa", "12°49′48″B", "109°23′27″Đ", "", 16),
( 407, "Hòn Giôm", "12°48′53″B", "109°21′48″Đ", "", 16),
( 408, "Hòn Trâu", "12°45′15″B", "109°20′35″Đ", "", 16),
( 409, "Hòn Cổ", "12°45′01″B", "109°18′13″Đ", "", 16),
( 410, "Hòn Mao", "12°44′23″B", "109°19′45″Đ", "", 16),
( 411, "Hòn Một", "12°43′51″B", "109°19′10″Đ", "", 16),
( 412, "Hòn Bịp", "12°43′04″B", "109°18′01″Đ", "", 16),
( 413, "Hòn Trì", "12°42′22″B", "109°22′00″Đ", "", 16),
( 414, "Hòn Á", "12°42′19″B", "109°17′19″Đ", "", 16),
( 415, "Hòn Đuốc", "12°41′54″B", "109°16′54″Đ", "", 16),
( 416, "Hòn Vung", "12°40′40″B", "109°15′44″Đ", "", 16),
( 417, "Hòn Khô", "12°39′30″B", "109°24′08″Đ", "", 16),
( 418, "Hòn Đôi", "12°39′14″B", "109°27′58″Đ", "", 16),
( 419, "Hòn Ông", "12°39′05″B", "109°23′39″Đ", "", 16),
( 420, "Hòn Sẵng", "12°38′50″B", "109°20′31″Đ", "", 16),
( 421, "Hòn Đỏ", "12°38′45″B", "109°22′28″Đ", "", 16),
( 422, "Hòn Kê", "12°38′37″B", "109°18′56″Đ", "", 16),
( 423, "Hòn Khô", "12°38′25″B", "109°19′22″Đ", "", 16),
( 424, "Hòn Mài", "12°38′17″B", "109°17′34″Đ", "", 16),
( 425, "Hòn Đụng", "12°38′14″B", "109°18′23″Đ", "", 16),
( 426, "Hòn Me", "12°38′09″B", "109°17′57″Đ", "", 16),
( 427, "Hòn Khô", "12°37′14″B", "109°26′10″Đ", "", 16),
( 428, "Hòn Lớn", "12°36′10″B", "109°21′54″Đ", "", 16),
( 429, "Hòn Thâm", "12°35′55″B", "109°18′10″Đ", "", 16),
( 430, "Hòn Khô Tran", "12°35′48″B", "109°26′47″Đ", "", 16),
( 431, "Hòn Đen", "12°34′31″B", "109°26′25″Đ", "", 16),
( 432, "Hòn Trâu Nằm", "12°33′55″B", "109°27′43″Đ", "", 16),
( 433, "Hòn Tai", "12°32′53″B", "109°23′28″Đ", "", 16),
( 434, "Hòn Theo", "12°29′38″B", "109°19′36″Đ", "", 16),
( 435, "Hòn Mỹ Giang", "12°29′25″B", "109°17′54″Đ", "", 16),
( 436, "Hòn Đỏ", "12°28′59″B", "109°21′09″Đ", "", 16),
( 437, "Hòn Lửa", "12°28′40″B", "109°22′26″Đ", "", 16),
( 438, "Hòn Khô", "12°28′37″B", "109°18′16″Đ", "", 16),
( 439, "Hòn Cóc", "12°24′43″B", "109°10′21″Đ", "", 16),
( 440, "Hòn Cò", "12°24′26″B", "109°10′19″Đ", "", 16),
( 441, "Hòn Lăng", "12°24′10″B", "109°13′02″Đ", "", 16),
( 442, "Hòn Nứa", "12°24′08″B", "109°12′07″Đ", "", 16),
( 443, "Hòn Giữa", "12°24′01″B", "109°13′19″Đ", "", 16),
( 444, "Hòn Thị", "12°23′25″B", "109°13′52″Đ", "", 16),
( 445, "Hòn Sầm", "12°23′10″B", "109°13′00″Đ", "", 16),
( 446, "Hòn Chà Là", "12°21′39″B", "109°22′30″Đ", "", 16),
( 447, "Hòn Bạc", "12°20′17″B", "109°18′55″Đ", "", 16),
( 448, "Hòn Lao", "12°21′37″B", "109°12′50″Đ", "", 16),
( 449, "Hòn Rùa", "12°17′23″B", "109°14′32″Đ", "", 16),
( 450, "Hòn Câu", "12°16′57″B", "109°22′04″Đ", "", 16),
( 451, "Hòn Dung", "12°16′13″B", "109°21′34″Đ", "", 16),
( 452, "Cù lao Thượng", "12°16′02″B", "109°12′26″Đ", "", 16),
( 453, "Hòn Đá Chữ", "12°15′43″B", "109°12′08″Đ", "", 16),
( 454, "Hòn Tre", "12°12′46″B", "109°17′11″Đ", "", 16),
( 455, "Hòn Miểu", "12°11′23″B", "109°13′25″Đ", "", 16),
( 456, "Hòn Một", "12°10′39″B", "109°16′17″Đ", "", 16),
( 457, "Hòn Tằm", "12°10′35″B", "109°14′30″Đ", "", 16),
( 458, "Hòn Mun", "12°10′06″B", "109°18′03″Đ", "", 16),
( 459, "Đảo Bình Ba", "11°50′14″B", "109°14′06″Đ", "", 16),
( 460, "Đảo Bình Hưng", "11°46′45″B", "109°13′01″Đ", "", 16),
( 461, "Hòn Nội", "12°02′21″B", "109°19′20″Đ", "", 16),
( 462, "Hòn Ngoại", "12°00′20″B", "109°19′15″Đ", "", 16),
( 463, "Hòn Tai", "11°53′58″B", "109°16′06″Đ", "", 16),
( 464, "Hòn Xây", "11°51′49″B", "109°14′20″Đ", "", 16),
( 465, "Hòn Giảng", "11°51′45″B", "109°16′17″Đ", "", 16),
( 466, "Hòn Khô", "11°50′23″B", "109°10′48″Đ", "", 16),
( 467, "Hòn Mũi", "11°49′01″B", "109°12′01″Đ", "", 16),
( 468, "Hòn Trứng", "11°47′28″B", "109°12′23″Đ", "", 16),
( 469, "Hòn Sam", "11°46′13″B", "109°13′22″Đ", "", 16),
( 470, "Hòn Cột Buồm", "11°43′19″B", "109°13′36″Đ", "", 17),
( 471, "Hòn Tai", "11°42′58″B", "109°13′10″Đ", "", 17),
( 472, "Hòn Đeo", "11°38′59″B", "109°10′29″Đ", "", 17),
( 473, "Hòn Lìu", "11°34′57″B", "109°08′08″Đ", "", 17),
( 474, "Hòn Chông", "11°34′51″B", "109°08′41″Đ", "", 17),
( 475, "Hòn Đỏ", "11°33′58″B", "109°07′48″Đ", "", 17)


create table restaurants (
  id int not null, 
  name varchar(255),
  primary key(id)
)

insert into restaurants
(id, name)
values
(0, "Nhà hàng Talata"),
(1, "Nhà hàng Hương 2"),
(2, "Nhà hàng Nhất Chiêu Lạng Sơn"),
(3, "Nhà hàng 6S Beer Garden"),
(4, "Nhà hàng Hồng Hạnh 2"),
(5, "Nhà hàng bia 365"),
(6, "Nhà hàng ThaChang"),
(7, "Nhà hàng TaCo Bay"),
(8, "Nhà hàng Hương Duyên"),
(9, "Nhà hàng Khải Hương"),
(10, "Nhà hàng Bến Du Thuyền"),
(11, "Nhà hàng Phương Nam"),
(12, "Nhà hàng Thiên Anh"),
(13, "Nhà hàng Cua Vàng"),
(14, "Nhà hàng Thủy Chung"),
(15, "Nhà hàng Phương Thuỷ"),
(16, "Nhà hàng Hồng Hạnh 3"),
(17, "Nhà hàng Ngọc Lục Bảo"),
(18, "Nhà hàng Sen Á Đông")


create table restaurants_islands(
  restaurantId int not null,
  islandId int not null,
  primary key(restaurantId, islandId)
)

insert into restaurants_islands
(islandId, restaurantId)
values
(12, 0),
(12, 1),
(12, 2),
(12, 3),
(12, 4),
(12, 5),
(12, 6),
(12, 7),
(12, 8),
(12, 9),
(33, 0),
(33, 1),
(33, 2),
(33, 3),
(33, 4),
(33, 5),
(33, 6),
(33, 7),
(33, 8),
(33, 10),
(53, 11),
(53, 12),
(53, 13),
(53, 14),
(53, 15),
(53, 16),
(53, 17),
(53, 10),
(53, 18),
(53, 9),
(57, 0),
(57, 1),
(57, 2),
(57, 3),
(57, 4),
(57, 5),
(57, 6),
(57, 7),
(57, 8),
(57, 9),
(58, 0),
(58, 1),
(58, 2),
(58, 3),
(58, 4),
(58, 5),
(58, 6),
(58, 7),
(58, 8),
(58, 9)


create table places(
  id int not null,
  name varchar(255) not null,
  islandId int not null,
  primary key(id)
)

insert into places
(id, name, islandId)
values
(0, "Đồi cát pha lê", 12),
(1, "Eo Gió Gót Beo", 12),
(2, "Miếu thờ Trần Khánh Dư", 12),
(3, "Rừng Trâm", 12),
(4, "Thương cảng cổ Vân Đồn", 12),
(5, "Đình Quan Lạn", 12),
(6, "Bãi biển Sơn Hào", 12),
(7, "Bãi tắm Robinson", 12),
(8, "Bãi tắm Quan Lạn", 12),
(9, "Bãi Rùa (bãi nhánh Rìa)", 12),
(10, "Bãi tắm Minh Châu", 12),
(11, "Bãi biển Cồn Khởi", 12),
(12, "Bãi tắm Trường Chinh", 33),
(13, "Bến Cống Yên", 33),
(14, "Hồ nước ngọt trên đảo Ngọc Vừng", 33),
(15, "Khu lưu niệm Bác Hồ", 33),
(16, "Thành cổ Ngọc Vừng", 33),
(17, "Bãi tắm Tuần Châu", 53),
(18, "Công viên King Kong", 53),
(19, "Sân khấu biểu diễn cá heo Tuần Châu", 53),
(20, "Phố đi bộ Paradise", 53),
(21, "Sân khấu nhạc nước Tuần Châu", 53),
(22, "Tuần Châu Park", 53),
(23, "Bãi biển Vàn Chảy", 57),
(24, "Ngọn hải đăng Cô Tô", 57),
(25, "Khu Di tích lưu niệm Hồ Chủ tịch trên đảo Cô Tô", 57),
(26, "Con đường Tình Yêu", 57),
(27, "Đảo Cô Tô Con", 57),
(28, "Cầu Gỗ", 57),
(29, "Bãi đá Cầu Mỵ (Bãi Đá Móng Rồng)", 57),
(30, "Bãi biển Tình Yêu", 57),
(31, "Bãi biển Hồng Vàn", 57),
(32, "Phố đi bộ Ký Con", 57),
(33, "Bãi biển Ba Châu", 58),
(34, "Bãi biển Hải Quân", 58),
(35, "Nhà Thờ Thanh Lân", 58)






